### ISSUE TITLE
資材ログの質問

### ISSUE THREAD

**Issue by nchu-luke** [sanaehirotaka/logbook-kai#1]
Good morning, i am logbook user and i come from Taiwan.
Recently you release  logbook-kai, so i change from old version.
And then  i move 資材ログ to  logbook-kai's folder to inherit the log.
But,i found something wrong when i use 資材チャート.
the number of 高速修復剂and高速建造材 swap like this picture
http://i.imgur.com/pwDXA4w.jpg 
I don't know how to deal with it, maybe  is a bug.
I'm sorry, my Japaneses is bad, so i use English.

**Comment by sanaehirotaka** [comment]
ありがとうございます、ログの保存で高速修復材と高速建造材の順番が誤っていました

**Comment by 0x0003** [comment]
非常に細かいところなのですが、資材ログの「高速修復材」表記が「高速修復剤」になっています。
次回更新時のついでで結構ですので修正頂ければと。

**Comment by sanaehirotaka** [comment]
ありがとうございます、修正しました。
