### ISSUE TITLE
所有艦娘一覧のソートについて

### ISSUE THREAD

**Issue by fubuki-t** [sanaehirotaka/logbook-kai#100]
便利なツールを作っていただいてとても助かっています。ありがとうございます。

所有艦娘一覧の艦娘の列を名前でソートしようとすると、自然順じゃないIDのソートになってしまいます。
こちらの環境だけでしか起らない事かもしれず申し訳ありませんが、ご確認よろしくお願いいたします。

航海日誌は18.10.2、javaは1.8.0_181-b13を使っています。

**Comment by sanaehirotaka** [comment]
あーIDを文字列として評価したソートになってますね。
艦娘の名前ソートのほうが自然なので直します。
