### ISSUE TITLE
所有艦娘一覧のテキストフィルター機能について

### ISSUE THREAD

**Issue by momidi** [sanaehirotaka/logbook-kai#101]
いつも便利に利用させていただいております。

さて、首記の通り所有艦娘一覧のテキストフィルター機能についてなのですが、
改二改装済みの艦だけを抽出しようと”改二”を打ち込むと”長月改””朝風改”など一部改二でない艦が出てしまいます。
フィルター機能の確認・修正をお願いします。

**Comment by sanaehirotaka** [comment]
テキストフィルターは艦娘の名前の他、艦種や装備の名前も検索対象になっていますので
恐らく装備の12.7cm連装砲○型改二などがヒットしたのだと思われます。

**Comment by momidi** [comment]
確認しました。装備なども対象となっていとは知りませんでした申し訳ありません。

**Comment by sanaehirotaka** [comment]
ご確認ありがとうございます
解決ということで一旦issueを閉めさせていただきます
