### ISSUE TITLE
戦闘ログの保存機能についての要望

### ISSUE THREAD

**Issue by kPherox** [sanaehirotaka/logbook-kai#102]
# 保存期間の要望
現在の戦闘ログは集計期間の追加によって過去の記録も見ることができるようになっていますが、60日以前を過ぎたログの詳細は確認できません（設定ファイルを直接書き換えれば保存期間の変更は可能？）
なので以下の機能の実装を検討していただきたいと思います

- 設定に戦闘ログの保存期間の項目を追加
- 戦闘ログを半永久的に保存するオプション

# 圧縮に関する要望
すでに保存されている戦闘ログを圧縮したいので`battlelog/<DATE>.json.gz`というファイル名をサポートしていただきたいと思います

**Comment by sanaehirotaka** [comment]
戦闘ログ詳細の仕様を次のように変更する予定です
 - jsonの保存先を`battlelog`から`battlelog/yyyy-MM`に変更
   - 保存されるタイミングで既存のjsonが`battlelog`から`battlelog/yyyy-MM`に移動される。(初回は～10秒程度掛かる見込み)
 - 設定画面に保存期間、保存期間を無期限にする設定を追加
 - 圧縮のオプションが有効の場合は拡張子を`.json.gz`にする
ご意見あればよろしくおねがいします。

**Comment by kPherox** [comment]
> - jsonの保存先を`battlelog`から`battlelog/yyyy-MM`に変更
>   - 保存されるタイミングで既存のjsonが`battlelog`から`battlelog/yyyy-MM`に移動される。(初回は～10秒程度掛かる見込み)

これは`battlelog/2018-10-09 19-42-52.json`が`battlelog/2018-10/2018-10-09 19-42-52.json`という形になるという理解で違いないですか？
初回の移動時間は許容できる速さだと思います

他二つは要望通りなのでその形でいいと思います

**Comment by sanaehirotaka** [comment]
> これは`battlelog/2018-10-09 19-42-52.json`が`battlelog/2018-10/2018-10-09 19-42-52.json`という形になるという理解で違いないですか？
はいそれで違いありません、単純にフォルダに移動されるだけでファイル名は変更されません。

フォルダを移動させる理由としては、jsonが任意の期間保存されるようになることによって、期限切れで削除になるjsonを探すためのI/O負荷が高くなってしまう懸念があるためです。

**Comment by kPherox** [comment]
わかりました。これ以上気になる点はないのであとはお任せします

**Comment by kPherox** [comment]
18.10.4でリリースされたので閉じます
