### ISSUE TITLE
最新バージョンの取得に失敗

### ISSUE THREAD

**Issue by sherry0757** [sanaehirotaka/logbook-kai#104]
ログファイルです。
[app.txt](https://github.com/sanaehirotaka/logbook-kai/files/2551589/app.txt)
Linux Mint 19 mate 64bit oracle 1.8.0_181

**Comment by sanaehirotaka** [comment]
ありがとうございます。アップデート確認用サーバーの証明書に不備がありました。
修正して現在はこのようなログが出ることはなくなっています。
