### ISSUE TITLE
修復/遠征のバナー表示がおかしくなる(bug)

### ISSUE THREAD

**Issue by chatani917** [sanaehirotaka/logbook-kai#107]
いつもありがたく使わせていただいてます。
表題のとおり、バナー表示がおかしくなる事象を確認しましたのでご報告します。

艦娘の状態を表すオーバーレイ？のアイコンがずれるようです。
今回の事象ですと「修復」は「撃沈」で表示され、「遠征」は「大破」と表示されています。
「小破」「中破」「大破」は正しく表示されます。

約1ヶ月ほど出張していたため、航海日誌の起動は1ヶ月ぶりでしたが以前は問題ありませんでした。

問題の確認後に航海日誌のバージョンUP、ブラウザバージョンUP、キャッシュ削除を試してみましたが戻りません。
このあとresources/commonの中身を削除し、再度キャッシュ削除で問題は解消しました。

現在のところ再発はしていません。
他に必要な情報がありましたらご連絡ください。
問題は解消してますので特に対応が不要ということであればこのままクローズしてもらっても大丈夫です。

---
**環境**
- 航海日誌 18.11.1（up前：18.10.4）
- Chrome 70.0.3538.110(64bit)
- Windows8.1 Pro

**Comment by sanaehirotaka** [comment]
こんにちは
航海日誌が画像の変更をキャッチできていないことが稀にあるようです
対策を考えてはいますが今の所完全に防ぐのは難しいです。

**Comment by sanaehirotaka** [comment]
小さなアイコンなどの画像を1つの画像にまとめた「画像ファイル」とそれを切り出すための情報を持っている「スプライト情報ファイル」
この2つのファイルが書き込まれた日時を確認して両方とも更新がされている場合にバナーアイコンを更新するように処理を修正してみました。
恐らく、おかしくなる可能性が減ると思います。

**Comment by mousagi** [comment]
いつも使わせて頂いてます。
昨日からここの表題のバグが私の環境でも発生して、上の通りresources/commonの中身とキャッシュを削除したら装備と艦娘の状態のアイコンが表示されなくなりました
ソフト再インストールしなければ元に戻らないのでしょうか？バージョンアップが来たら戻りますか？

**Comment by sanaehirotaka** [comment]
こんにちは。
この問題を改善したv18.12.1をリリースしました。
バージョンアップ後、ブラウザキャッシュを削除＆ブラウザを再起動しゲームを再スタートしてみてください。

**Comment by kikurinkei** [comment]
私も11月16日ごろのメンテ（戦果修正のメンテ）の後に、小破→中破　中破→大破　大破→轟沈　という感じに「艦娘の上にのせてあるマーク？」がズレていました。
ここに書き込もうかと考えましたが、だれも書いてなかったので、私だけの環境での発生と思いそのままスルーしておきました。3日ぐらいたったら勝手に治ってました。さんこうになれば。
（WIN10PRO/クローム）
