### ISSUE TITLE
現在の戦闘で敵の制空値を見たい

### ISSUE THREAD

**Issue by headsupsevens** [sanaehirotaka/logbook-kai#109]
現在の戦闘画面に、敵の制空値を表示していただけないでしょうか。

**Comment by sanaehirotaka** [comment]
既に判明している海域の敵制空値は制空状態（喪失～確保）と現在の制空値から検証して得られた数値ですのでデータとして敵の制空値は持っておりません。
データベースを作成し、検証済みの制空値を表示することは不可能ではありませんが手間がかかるため今の所表示する予定はありません

**Comment by headsupsevens** [comment]
了解しました。
敵の艦載機のデータが送られてくるわけではないんですね。
ありがとうございました。
