### ISSUE TITLE
母港画面で各艦隊のコンディション値が一覧で見えるよう

### ISSUE THREAD

**Issue by sobant** [sanaehirotaka/logbook-kai#113]
母港画面で各艦隊に所属している艦のコンディション値を一覧で表示出来ると、
いちいち個別の艦隊タブを表示しなくてもよくなるのでご検討ください。

**Comment by Sdk0815** [comment]
要望ありがとうございます。現在のバージョンは「ワイド」というスタイルも選択可能ですので、以下のように（一つの艦隊だけですが）コンディション値を含め艦隊の情報が母港画面と同時に見えるようになっております。
![image](https://user-images.githubusercontent.com/3181895/87215177-be9cfe00-c36e-11ea-87b4-4e78e1bc503a.png)
母港タブと艦隊タブを行き来するのが面倒という場合でしたらこちらをご活用いただければと思います。

すべての艦隊のコンディション値を一覧で見たいというご要望でしたら現状では対応できておりませんが検討してみますのでその旨お知らせください。よろしくお願いします。

**Comment by Sdk0815** [comment]
こちらの issue はいったん close させていただきます。もし上記のご要望がありましたら別 issue を上げていただければと思います。よろしくお願いします。
