### ISSUE TITLE
HPの数値表示

### ISSUE THREAD

**Issue by Sdk0815** [sanaehirotaka/logbook-kai#12]
Issue というより Feature Request ですが、オプションでもいいので旧版にあったHPの数値表示を実装していただけないでしょうか。ゲージだけだとカスダメをもらってる艦と無傷な艦の区別がつきにくかったり、泊地修理中にあと何HP回復する必要があるのかが一目でわからなくなったりするので、具体的に数値で表示できるようになると嬉しいです。こんな感じのイメージです↓

![2016-04-30 11 49 17](https://cloud.githubusercontent.com/assets/3181895/14933433/ab09d934-0ec9-11e6-9099-1a4d3cb68d77.png)

「小破」とかの文字はすでにバナーのところに出てるのでいらなさそうですが、「健在」はそういえば何も表現されてないなと思って一応表示したイメージにしてみました。ゲージや文字の色を変えるとかでもよいかもしれません。

ご検討のほどよろしくお願いいたします。（不要だとの判断であれば実装せずに Close していただいても結構です。）

**Comment by sanaehirotaka** [comment]
名前の横に表示すると名前の長い艦娘(Graf Zeppelin改など)が見づらくなってしまうので燃料弾薬ゲージの横に置こうと考えています。
![default](https://cloud.githubusercontent.com/assets/2179301/14934502/ce834cf6-0eec-11e6-8603-6bc92c3e4a84.png)
小破・中破などの表示はスペースが無いので今のところ保留したいです

**Comment by Sdk0815** [comment]
確かにそのほうが名前が見やすくてよいですね。上にも書きましたが小破とかは冗長なのでなくてよいと思います。検討していただいてありがとうございます！

**Comment by sanaehirotaka** [comment]
こちらこそありがとうございます
