### ISSUE TITLE
資材チャートの横軸目盛りの再レンダリング

### ISSUE THREAD

**Issue by SSW-SCIENTIFIC** [sanaehirotaka/logbook-kai#13]
v0.0.12をWindowsで利用中です。

現在, 資材チャートにてグラフ表示期間の開始/終了をそれぞれ選択した場合にグラフの横軸の再レンダリングが行われません。
`ResourceChartController.java`の, 期間のリストボックス選択時のイベントハンドラ`changeScaleAction`内では横軸スケール修正のコードが含まれているようですが, 開始/終了の直接選択時の`changeAction`には同様のコードが含まれていないことが原因かと思います。

**Comment by sanaehirotaka** [comment]
PRありがとうございます。取り込みました
