### ISSUE TITLE
開発ログの件数、割合のソート順が数値でソートされていない

### ISSUE THREAD

**Issue by nomonomo** [sanaehirotaka/logbook-kai#133]
開発ログの件数、割合のソートが数値でソートされていないようです
例)1,104,15,1509,162
投入資材→装備では、数値の方が良いのでは無いかと思います。

Ver19.2.2

**Comment by Sdk0815** [comment]
@nomonomo 修正がマージされました。次のバージョンがリリースされましたら確認可能です。
