### ISSUE TITLE
遠征プログレスバーの色が紛らわしい

### ISSUE THREAD

**Issue by sherry0757** [sanaehirotaka/logbook-kai#134]
残り5分で変わる色が最後まで変わりなく紛らわしいです。

残り1分or帰投で明確にわかる色にしてほしいです。

**Comment by Sdk0815** [comment]
@sherry0757 報告ありがとうございます。確かに5分より1分のほうが大事なので、1分で濃い黄色（今5分になると変わる色）に変わるように変更します。

**Comment by Sdk0815** [comment]
変更が取り込まれました。次のバージョンで修正されます。よろしくお願いします。
