### ISSUE TITLE
艦隊タブの損害状況別カラーが分かりづらい

### ISSUE THREAD

**Issue by naoto-seki** [sanaehirotaka/logbook-kai#136]
現状。

出撃中：黄色
中破艦あり：オレンジ
大破艦あり：赤

になっていると思うが、黄色とオレンジの差がわかりにくい。

全員無傷：緑
カスダメ～小破：黄色（黄緑でも良い）
中破：濃いオレンジ（現状黄色と違いが分かりづらい）
大破：赤

になるとわかりやすいです。
※自分で色指定できても良いです。

**Comment by naoto-seki** [comment]
自己解決というか個人的応急対応
jarファイルを適当な解凍ツールで開いて
logbook\gui\main.css を取り出す。
20-40行目辺りのスタイルシートをちょっといじる。で対応しました。
`/* 大破 */
TabPane .tab.alert {
    -fx-background-color: linear-gradient(from 25% 25% to 100% 100%, #FF0000, transparent);
}
TabPane .tab.alert .tab-label {
    -fx-text-fill: white;
}
/* 中破 */
TabPane .tab.warn {
    -fx-background-color: linear-gradient(from 25% 25% to 100% 100%, #FF7F00, transparent);
}
TabPane .tab.warn .tab-label {
}
/* 小破以下破（1戦目以降） */
TabPane .tab.shortage {
    -fx-background-color: linear-gradient(from 25% 25% to 100% 100%, #7FFF7F, transparent);
}
TabPane .tab.shortage .tab-label {
}
/* 未出撃 */
TabPane .tab.empty {
    -fx-background-color: linear-gradient(from 25% 25% to 100% 100%, #87CEFA, transparent);
}`

**Comment by Sdk0815** [comment]
@naoto-seki 報告ありがとうございます。現状は正確には

~出撃中~ 未補給の艦がいる場合：黄色
中破艦あり：オレンジ
大破艦あり：赤
第二艦隊以降で遠征や連合艦隊編成に含まれていない場合：青

になっています。単純にダメージのみで色を決めているわけではないため、ご要望にそのままお応えすることができないのですが、オプションにするなど内容を含め改善を検討したいと思います。

**Comment by Sdk0815** [comment]
@naoto-seki 変更が取り込まれました。次のバージョンで確認可能になります。
