### ISSUE TITLE
所有艦娘一覧における艦娘名とサムネイルの分割

### ISSUE THREAD

**Issue by naoto-seki** [sanaehirotaka/logbook-kai#138]
現状「艦娘」のカラムでサムネイル(装備含む)＋艦名を表示していますが、これを「サムネイル」と「艦名」に分割していただきたいです。

これは環境などにも依存するのかもしれませんが、画像を読み込む関係か画像表示時と非表示時で艦種絞り込みや特定項目での並び替えなどの処理速度がかなり違うので、画像を読み込まない設定がほしいです。

**Comment by Sdk0815** [comment]
@naoto-seki 現行バージョンでは画像を読み込まない設定が可能になっていますのでご確認ください。

サムネイルと艦名は引き続き同じカラムに表示していますが、分ける利点は何かありますでしょうか？利点があるようでしたら検討しますので、別 issue を上げて理由を記述していただければと思います。よろしくお願いします。
