### ISSUE TITLE
疲労回復の予想時間が表示されない事がある

### ISSUE THREAD

**Issue by kakkou** [sanaehirotaka/logbook-kai#140]
ver19,9,3

condが49を下回っている艦がいるのに母港と出撃画面を行き来しても
疲労回復の予想時間が表示されない事があります。
少し待ってから母港と出撃画面を行き来すれば表示されたりもしますが条件がわかりません。

![49](https://user-images.githubusercontent.com/696724/65373904-7ec13900-dcbe-11e9-8521-a14c4ab88d0b.PNG)

**Comment by Sdk0815** [comment]
報告ありがとうございます。まだ確認中ではありますが、恐らく条件は
- 出撃前に出撃する艦隊に所属しておらず、かつ cond 値が 49 未満の艦がいない
- 出撃した艦隊に所属している艦の、帰投する直前の cond 値は全艦 50 以上である
  - 例えば全艦49以上で出撃し、道中A勝利以上、S勝利(cond 値 +1)を1回以上であればこの条件を満たすことになります
- 帰投した後、出撃した艦の中に cond 値が 49 未満の艦がいる

この条件を満たした場合に疲労回復が表示されない、または予定時刻が大幅にずれるように思われます。この後 cond 値が変更するような動作（自然回復、出撃、演習、cond 値40以下の艦の入渠など）が発生して母港に戻るとそこからまた表示されるようになるようです。

対応を検討中ですが、対応が完了したとしても、艦これの仕様上いつを起点にして cond 値が 3 回復するのかはわからないので、どうしても最大3分の誤差が生じることはご容赦いただけると幸いです。

**Comment by Sdk0815** [comment]
@kakkou 修正を行いました。次のバージョンに含まれる予定です。
