### ISSUE TITLE
戦闘ログについて

### ISSUE THREAD

**Issue by P-9821** [sanaehirotaka/logbook-kai#141]
海域には1-1　5-5とか旧来の表記の列　旗艦及びMVPの列
母港には任務での「現在受けてる任務」以外の表記の追加
任務の進捗状況の拡充　特にクォータリー出撃任務では「未消化海域を小さく表記」なんかの機能があるとありがたいです

**Comment by Sdk0815** [comment]
戦闘ログにカラムを増やすのは結構大改修が必要なため今回は保留させてください。また、３番目のご要望に関しては母港の画面幅に入れるのが難しいのでこちらも保留させていただきます。

２番目の受諾中以外の任務を表示する機能については実装する予定です。
