### ISSUE TITLE
アップデートキャンセル時のメッセージボックスについて

### ISSUE THREAD

**Issue by kuuzya** [sanaehirotaka/logbook-kai#144]
タイトル部分にメッセージがありますが、メッセージボックス内部にも同様のメッセージが欲しいです。

**Comment by Sdk0815** [comment]
@kuuzya 報告ありがとうございます。すみません「アップデートキャンセル時のメッセージボックス」というのはどのウィンドウのことを指しておられますでしょうか？もしかしたら過去のバージョンで出ていたのかもしれませんが、少なくとも現行のバージョンだと
![image](https://user-images.githubusercontent.com/3181895/87214811-04f05e00-c36b-11ea-84b3-f7f465094643.png)
ここで「後で」をクリックしても特に何も出てこないので @kuuzya さんがどの部分を指摘されているのかわかっておりません。追加情報をいただけると助かります。よろしくお願いします。

**Comment by Sdk0815** [comment]
とりあえずいったん close させていただきます。もしまだ改良のご要望があるようでしたら遠慮なく別の issue を上げていただければと思います。よろしくお願いします。
