### ISSUE TITLE
編成記録の左下にある「艦隊」の並び替えなどの要望です

### ISSUE THREAD

**Issue by KanColle1** [sanaehirotaka/logbook-kai#145]
始めまして。いつも大変便利に活用させていただき感謝しております。

編成記録の左上の編成一覧についてはすでに並び替えが実装されておりますが
左下の「艦隊」のところの並び替えについても、実装していただければなと思っております。
また、「艦隊」のところの名前一覧をクリックすると右の艦隊表示がスクロールしてくれると嬉しいです。

ご検討の方よろしくお願いいたします。

もう一つ、大破進撃時の通知の時に
「通知でサウンドを鳴らす」がOFF時でも音が鳴りますが自分の環境だけなのか
もしくはそういう仕様なのでしょうか？

**Comment by Sdk0815** [comment]
@KanColle1 遅くなりましたが上記のご要望の件、実装を完了しました。次のバージョンから利用可能になります。

大破進撃の警告については（私が実装したわけではないので作者さんの意図した通りかどうかはわからないのですが）大破進撃の警告は非常に重要であるため常に音を鳴らすようになっているのだと思っています。ですがもちろん技術的には音が出ないようにすることも可能ですので、是非実装してほしい場合は別途 Issue を上げていただければと思います。よろしくお願いします。
