### ISSUE TITLE
【修正希望】所有装備数について

### ISSUE THREAD

**Issue by flora058** [sanaehirotaka/logbook-kai#148]
最大保有装備数がゲーム内と航海日誌で"13"ずれています。

環境　os:win10 ブラウザ google chrome　プロキシ設定　SwitchySharp Options

**Comment by Sdk0815** [comment]
@flora058 報告ありがとうございます。こちらではそのような現象は確認できておりませんが、今でも問題は存在しておりますでしょうか？ご確認よろしくお願いします。

**Comment by Sdk0815** [comment]
更新がないようですのでいったん close とさせていただきます。引き続き問題が継続している場合は別 issue を上げていただけると助かります。よろしくお願いいたします。
