### ISSUE TITLE
【要望】各種表示の要望

### ISSUE THREAD

**Issue by P-9821** [sanaehirotaka/logbook-kai#150]
前の航海日誌にあった

・各艦隊艦艇の予測回復時間までのカウントダウン表示機能
・各艦隊に編成されてる艦艇の次レベルアップまでの経験値進捗表示バー
・開発ログの日付別開発結果の表示（今日は何が開発できたっけ？を見やすく）
・戦闘ログの各海域名称の他に1-1　5-3　などのナンバー表示の切り替え選択
・戦闘ログの単純な日付日時順の表示

機能の実装をお願いしたく

**Comment by Sdk0815** [comment]
各種ご要望について
- 疲労回復時間：カウントダウンはないですが、代わりに各艦隊に疲労回復時間が表示されています
- 経験値進捗バー：実装済です
- 開発ログの日付別開発結果：全件表示可能になったので右のテーブルを日付でソートしてご確認ください
- 戦闘ログの数字表示：海域名に(1-1)のように付与されており、デフォルトのソート順はその数字順になっております
- 戦闘ログの日付順の表示：デイリー、ウィークリーなどを選択し日付でソートしてご確認ください
