### ISSUE TITLE
【要望】動画キャプチャの自動録画開始停止機能

### ISSUE THREAD

**Issue by Uchio** [sanaehirotaka/logbook-kai#151]
出撃時　出撃開始ボタンを押した後（出撃が確認できた後の何らかのタイミング）で録画開始
帰港時　母港に戻ったら録画停止
のような機能を要望いたします。
毎回出撃時　母港へ帰港時に手動でやってますが押し忘れてちょっと寂しい感じなので
出来れば実装を希望いたします。

**Comment by Sdk0815** [comment]
@Uchio だいぶ時間が経ちましたがこちら実装しました。次のバージョンで利用可能になります。よろしくお願いします。

**Comment by Uchio** [comment]
g装の方ありがとうございます！
ぜひ使用させていただlきます。


Windows 10 版のメ`ル<https://go.microsoft.com/fwlink/?LinkId=550986>から送信

差出人: Sdk0815<mailto:notifications@github.com>
送信日r: 2020年9月27日 18:37
宛先: sanaehirotaka/logbook-kai<mailto:logbook-kai@noreply.github.com>
CC: Uchio<mailto:uchio_wrc@hotmail.com>; Mention<mailto:mention@noreply.github.com>
件名: Re: [sanaehirotaka/logbook-kai] 【要望】踊悭抓隶悚巫渝h画_始停止C能 (#151)


@Uchio<https://github.com/Uchio> だいぶrgがUちましたがこちらg装しました。次のバ`ジョンで利用可能になります。よろしくおいします。

―

**Comment by Sdk0815** [comment]
先ほど公開した `20.10.1` から利用可能です。よろしくお願いします。
