### ISSUE TITLE
戦果拡張任務！「Z作戦」前段作戦 の進捗count

### ISSUE THREAD

**Issue by PotechTW** [sanaehirotaka/logbook-kai#152]
本日"戦果拡張任務！「Z作戦」前段作戦"を片付けたのですが、一部の進捗がcountされませんでした。
![Uncounted](https://user-images.githubusercontent.com/59118463/71309921-8f618680-2448-11ea-8b7d-aa5a570d114e.PNG)
6-1は本日までに3回こなし、すでに緑checkがついている状態でした。
2-4, 6-3は任務一覧の達成率が上がっても緑checkがつきませんでした。
6-4はA勝利ではつかず、S勝利で緑checkとなり正常でした。
6-1をこなしたのは12月8日午後なので、v19.12.2以降のどこかから起こっているものかと思います。ご調査いただければと思います。

**Comment by PotechTW** [comment]
「Z作戦」後段作戦 の7-2も進捗がcheckされませんでした。
![キャプチャ](https://user-images.githubusercontent.com/59118463/71369213-02076900-25e5-11ea-9c7d-af2373fd2cce.PNG)
5-5, 7-2, 6-2 の順でこなして7-2だけ漏れた状態です。任務一覧の達成率は7-2達成時に50%がつきました。

**Comment by sanaehirotaka** [comment]
ご報告感謝いたします。

現在調査及び再現を行っております。

**Comment by sanaehirotaka** [comment]
戦果拡張任務！「Z作戦」後段作戦
>5-5, 7-2, 6-2 の順でこなして7-2だけ漏れた状態です。任務一覧の達成率は7-2達成時に50%がつきました。
原因がわかりました。7-2はボスマスが2つあり区別する必要があるためmapcellの番号(セル15)を指定していますが
v19.12.2の変更によりアルファベットでの指定(セル15→M)に変更する必要がありました。

戦果拡張任務！「Z作戦」前段作戦
>2-4, 6-3は任務一覧の達成率が上がっても緑checkがつきませんでした。
こちらは原因の調査中です。

**Comment by Sdk0815** [comment]
@PotechTW 7-2 のカウント漏れは `v19.12.5` 以降で修正されていると思いますのでご確認ください。2-4/6-3については現行バージョンで再現できておりませんが、こちらの issue は一旦 close しますので、もしまだ起きているようであれば別 issue を上げていただけますでしょうか？よろしくお願いします。
