### ISSUE TITLE
泊地周辺海域の安全確保を徹底せよ！の進捗カウント

### ISSUE THREAD

**Issue by pr0pela** [sanaehirotaka/logbook-kai#153]
お疲れ様です。いつも便利なアップデートに感謝致します。

任務の進捗でカウント漏れを発見したためご報告致します。
本日、”泊地周辺海域の安全確保を徹底せよ！”の任務を受託した後、
7-2-1ボスと7-2-2ボスを三回S勝利しましたが、
進捗確認画面において正常に記録されませんでした。
詳細は以下の画像の通りです。

![スクリーンショット 2019-12-23 00 54 06](https://user-images.githubusercontent.com/19162338/71324224-9ad3b100-251f-11ea-96f7-da69f74e5168.png)

お手隙の際に、ご調査頂けますと幸いです。
対応に感謝致します。どうぞよろしくお願い致します。

**Comment by sanaehirotaka** [comment]
ご報告感謝いたします。
現在調査及び再現を行っております。

**Comment by Sdk0815** [comment]
@pr0pela `v19.12.5`以降で修正されていると思いますので Close します。もしまだ問題がある場合は reopen してください。よろしくお願いします。
