### ISSUE TITLE
所有艦娘ウィンドウと戦闘ログのウィンドウが開かない

### ISSUE THREAD

**Issue by jam971** [sanaehirotaka/logbook-kai#154]
タイトル通りです。
Dockのアイコンを右クリックすると上記ウィンドウのタイトルは見えているので、
内部的にはどこかにウィンドウを出しているのかもしれません。
なお、Java 9は入っていません。

航海日誌19.12.5
Java 8 231-b11
MacOS 10.15.2

**Comment by jam971** [comment]
sdk0815様

ありがとうございます。
いつもお世話になっております。

java更新のタイミングかOSアップデート等のタイミングで設定が初期化されたようで、現在は発生しておりません。

ところで、もし可能であれば、アイテム上のマウスオーバーでポップアップするウィンドウを停止するオプションはつきませんでしょうか？
javaのウィンドウ範囲が実際のそれと異なっているようで、javaのウィンドウ外をマウスオーバーしてもポップアップしてしまい、結構邪魔になります。
困難でなく、ご面倒でなければ御一考お願いします。

本当にいつも感謝して使わせていただいています。
これからもよろしくお願いします。

jam971 拝

**Comment by Sdk0815** [comment]
@jam971 更新ありがとうございます。現在は発生していないとのことよかったです。

追記の件ですが、別の issue としてあげていただいてもよろしいでしょうか？実際どのような状況なのか、画面キャプチャなどでご説明いただけると助かります。単にオフにするオプションを作るのではなく根本的に何か解決できるかもしれませんので。よろしくお願いします。

**Comment by Sdk0815** [comment]
@jam971 元々の問題は現在起きてないとのことなのでこちらの issue はクローズさせていただきます。ポップアップの件はまだ起きているようであれば問題報告・要望を[こちらに](https://github.com/Sdk0815/logbook-kai/issues)別 issue として上げていただければと思います。よろしくお願いします。
