### ISSUE TITLE
フォントの設定について

### ISSUE THREAD

**Issue by aki25256969** [sanaehirotaka/logbook-kai#161]
win7からwin10に乗り換えてフォントにがたつきが出るようになりました。java、航海日誌再インストールでも症状変わらずです。
読めない事も無いのですが以前と比べると明らかにフォントが汚く表示されるようになったので設定からフォントを変更出来るよう希望します。

**Comment by Sdk0815** [comment]
報告ありがとうございます。すみません、がたつきとおっしゃっているのがどの程度なのか確認したいのですが、私の Windows 10 の環境だとこんな感じです：
![image](https://user-images.githubusercontent.com/3181895/87327492-1609bc80-c56f-11ea-9624-b2c1fd5a0e8f.png)

@aki25256969 さんの環境だとどのように見えているのか教えていただけると幸いです。

**Comment by aki25256969** [comment]
返信ありがとうございます。また、連絡が遅れて申し訳ありません。
PCの電源を落とし、再起動すると100%左の画像のようになります。Winを上書きインストールすると右の様な綺麗なフォントに戻ります。また、綺麗になった状態でもPCを再起動すると左の様に汚くなります。

現状はスリープからの復帰ならば綺麗な表示のままなのでスリープで運用しています。
私の環境だけなのか分からないのですが、対応が面倒ならばスルーして下さい。

2020年7月14日(火) 1:14 Sdk0815 <notifications@github.com>:

**Comment by Sdk0815** [comment]
@aki25256969 返答ありがとうございます。すみません、画像が添付されていないようなのでどの程度かわからないのですが、記述を読ませていただいた限りでは少なくとも logbook-kai 固有の問題ではなさそうなので対応は難しそうですね。私の環境も知り合いの何人かの環境も聞いてみましたが、そのような現象になっている環境は今のところ確認できておりません。すみません。

一つだけ関連するかもと思ったのは、私が持っている環境で１つだけ再起動すると ClearType の設定がクリアされてしまう環境があります。その場合、 logbook-kai の文字は変わってないように見えるのですが、ブラウザ等多くのアプリケーションの文字が汚く見えます。ClearType の設定を Windows の設定からやり直してアプリケーションを再起動すれば直ります。現象は違いますがもし参考になれば。

![image](https://user-images.githubusercontent.com/3181895/88751716-28047580-d193-11ea-9c00-279e2b21bea7.png)

**Comment by Sdk0815** [comment]
次のバージョン（`v20.9.2` の次）にてフォントの指定も可能になりますので、単純にフォントの問題であればそれが役に立つかもしれません。よろしくお願いします。
