### ISSUE TITLE
海域札の表示

### ISSUE THREAD

**Issue by ukatsuTEITOKU** [sanaehirotaka/logbook-kai#172]
logbook-kaiを、いつも便利に使わせていただいております
ありがとうございます。

ですが、今イベントの海域札が、表示されずに困っています。
お忙しいのかと思いますが、対応いただけますと幸いです。

バージョンは20.5.1を使用しており、
更新を確認で、最新と表示されているのですが、
既に対応済みで、アップデートができていないのでしたら申し訳ありません。

以上、よろしくお願い致します。

**Comment by Sdk0815** [comment]
@ukatsuTEITOKU お疲れ様です。ご報告ありがとうございます。

確認ですが「今イベントの海域札が、表示されず」という問題はこんな感じに表示されてしまう現象のことでしょうか？
![image](https://user-images.githubusercontent.com/3181895/86026082-f308e400-ba69-11ea-85f5-0657055d1360.png)

この現象であれば次のバージョンで修正される予定ですので、今しばらくお待ちいただければと思います。
![image](https://user-images.githubusercontent.com/3181895/86026227-1e8bce80-ba6a-11ea-932d-db200b159ec0.png)
（所有艦娘一覧等も同時に修正されます。）

もしほかの問題であればお知らせください。よろしくお願いします。

**Comment by Sdk0815** [comment]
@ukatsuTEITOKU 上記の問題は `v20.6.1` にて修正されました。更新して確認していただけますでしょうか？問題なければ Close をお願いします。

**Comment by ukatsuTEITOKU** [comment]
更新確認いたしました。対応ありがとうございました。
