### ISSUE TITLE
戦闘ログについて

### ISSUE THREAD

**Issue by Niko25252** [sanaehirotaka/logbook-kai#173]
お世話になってります。
イベント海域E2の戦闘ログが名前が同じなのか、１-２になってしまっています
見れないわけではないので、お直しいただける時間がありましたら、修正よろしくお願いします

**Comment by Sdk0815** [comment]
@Niko25252 ご報告ありがとうございます。確認ですが、こちらの画面で表示される海域名が「南西諸島沖(1-2)」になってしまっているということでしょうか？

![image](https://user-images.githubusercontent.com/3181895/86136638-4c831880-bb27-11ea-8415-13e7f25fe63e.png)

その場合E1(48-1)では起きていないということでしょうか？

お手数をおかけして申し訳ありませんが確認のほどよろしくお願いします。
（私はまだE1が終わっておらず確認できないのでお尋ねしております。）

**Comment by Niko25252** [comment]
返信遅れ申し訳ありません。画像の通り、E1は48-1となっていますが、E2は1-2となっています。私もE2攻略中なのでE3以降は分かりませんが、E2はこうなっています。
これはデイリー、ウィークリー、マンスリー、先週でも同じです。(先月は通常の1-2に出撃していないので分からないです)
![e2](https://user-images.githubusercontent.com/20009138/86153268-5c592780-bb3c-11ea-867a-09b9f22791be.JPG)

**Comment by Sdk0815** [comment]
@Niko25252 確認ありがとうございます。おそらく原因がわかりましたので次のバージョンで修正する予定です。

**Comment by Niko25252** [comment]
ありがとうございます！

**Comment by Sdk0815** [comment]
修正完了しました。次のバージョンで取り込まれる予定です。

**Comment by Sdk0815** [comment]
@Niko25252 バージョン `v20.7.1` をリリースしました。修正を確認していただけると助かります。ただ既に前のバージョンで記録されたデータは修正できないので、バージョンアップ後に出撃した分のみの対応となります。よろしくお願いします。

**Comment by Niko25252** [comment]
ありがとうございました！

2020年7月1日(水) 21:12 Sdk0815 <notifications@github.com>:
