### ISSUE TITLE
第2,3,4艦隊タブが大破表示になる

### ISSUE THREAD

**Issue by headsupsevens** [sanaehirotaka/logbook-kai#192]
### 問題概要
第1艦隊で大破艦が出た時、母港に戻ったら第2,3,4艦隊のタブまで大破表示になりました。
（第2,3,4艦隊には大破艦は居ません）
その後、第1艦隊の大破艦を修理しても第2,3,4艦隊のタブは大破表示のままです。
再起動しても変わりませんでした。

### 再現方法
今のところ、再現方法は不明です。
第2,3,4艦隊のタブの色が戻らないので、再現できませんでした。

### 本来予想される動作
第2,3,4艦隊のタブは遠征表示になるはずです。

### スクリーンショット
![image](https://user-images.githubusercontent.com/34375409/87491690-c5d04e80-c683-11ea-98c0-b44dbfae0a20.png)

タブの色の設定は変更しています。
![image](https://user-images.githubusercontent.com/34375409/87491753-e9939480-c683-11ea-89ca-779f8f477787.png)

### 動作環境
 - OS:Windows 10 Pro 1909
 - Java:1.8.0_241
 - Version:20.7.4

**Comment by Sdk0815** [comment]
@headsupsevens 報告ありがとうございます。各艦隊のタブはプログラム的には全く別に処理されているので、第一艦隊の大破の状態がほかの艦隊のタブの色に影響するとは考えにくいので、どこか別のところにバグがあるのではないかと疑っております。私のほうではまだ再現できていないので、もしこの後再現手順等判明したら追記していただけると助かります。また、ログに何か出ていないかの確認もよろしくお願いいたします。

**Comment by headsupsevens** [comment]
ありがとうございます。
今日は、ログは何も出ていませんでした。

少し違う現象なのですが、以下はタブの色の設定で大破を「red」にした状態です。

第2艦隊の遠征が帰ってきたタイミングで、第2艦隊のタブが赤くなりました。
![image](https://user-images.githubusercontent.com/34375409/87509592-d77a1c00-c6ac-11ea-846a-0456cef034cb.png)

第4艦隊の遠征が帰ってきた時も同様でした。
![image](https://user-images.githubusercontent.com/34375409/87509874-6dae4200-c6ad-11ea-8e9a-4239843e095a.png)

また、明石の燃料・弾薬ゼロにした状態で、編成画面で随伴艦一括解除すると、第1艦隊のタブが赤くなりました。
![image](https://user-images.githubusercontent.com/34375409/87510070-d4336000-c6ad-11ea-823b-d2ca71a06d43.png)

**Comment by headsupsevens** [comment]
無傷時に「conf.getTabColorBadlyDamage()」を参照しているのが原因かなと思ったのですが、いかがでしょうか。
https://github.com/sanaehirotaka/logbook-kai/blob/b05c14c141aec03a300a01d2a241e19085e9584c/src/main/java/logbook/internal/gui/FleetTabPane.java#L336

**Comment by Sdk0815** [comment]
@headsupsevens お恥ずかしい限りです。おっしゃる通りですね。再現しました。
![image](https://user-images.githubusercontent.com/3181895/87516271-16619f00-c6b8-11ea-8e61-a389c280e723.png)

次のバージョンで早急に修正します。ありがとうございました。

**Comment by Sdk0815** [comment]
@headsupsevens 修正をマージしました。次のリリースで修正されます。次のバージョンのリリースまで気になる場合はお手数ですが大破用の色設定をデフォルト（何も入力しない）にしておいていただけますでしょうか。そうすると無傷の時にはタブが無色になり、大破の時にも `red` と全く同じではないですが赤い色（艦これの「大破」バッジの色です）になります。

**Comment by headsupsevens** [comment]
早々の対応ありがとうございました。
