### ISSUE TITLE
【不具合】任務欄の受領中任務の表示が特定操作で消滅する

### ISSUE THREAD

**Issue by h-sugawara** [sanaehirotaka/logbook-kai#194]
### 問題概要
ver. 20.7.5 から任務欄の受領中任務の表示が特定操作で消滅する

### 再現方法
1. 任務画面を開く
2. 下記の二つの条件を同時に満たすタブを選択する
    1. 「全」または「遂行中任務」ではない
    2. 受領中の任務を含まない
3. 別の画面（母港など）に移動する

### 本来予想される動作
* 艦これ側の任務画面のどのタブのページへ遷移しても、航海日誌側の受領中任務の表示が消滅しない、かつ、一番上に表示されること
    * 艦これ側の任務画面以外の画面へ遷移したときも、航海日誌側は上記の状態を維持できること

### スクリーンショット
省略

### 動作環境
 - OS: Windows 10
 - Java: SE Runtime Environment 1.8.0_251
 - Version: 20.7.5

### その他
任務画面に行けば受領していない任務はわかりますので、UX/UX 的な観点においても、航海日誌側で艦これ画面と同じ挙動をする必要はないかと思います。この機能はomitするか、設定によって動くか選択できるように改善をお願いします。

**Comment by Sdk0815** [comment]
@h-sugawara 報告ありがとうございます。タブを選択した場合も任務が消滅するのは意図した動作ではありません（普段あの（縦のほうの）タブを使わないので確認が漏れていました）。次のバージョンで修正を行います。

受諾していない任務の表示につきましては、任務画面に行かなくても受諾してない任務を表示してほしいという要望が別にありましたのでこのままにしておこうと思います。修正を入れた後であれば受諾中の任務が常に上に表示されますので問題ないと思われますが、リストが長くなるのが嫌という意見が多いようでしたらオプションにすることも考えようと思います。

**Comment by Sdk0815** [comment]
@h-sugawara 修正をマージしました。近日中にリリースする次期バージョンで修正されます。ご報告ありがとうございました。
