### ISSUE TITLE
艦隊編成の出力について

### ISSUE THREAD

**Issue by mujo4920** [sanaehirotaka/logbook-kai#197]
### イベント攻略や海域攻略の編成をSNS等でアップできる画像出力をしたい

 艦娘のステータス一覧と装備の一覧が一緒に見れる形式（3行2列）による編成画像を出力する機能があると嬉しいです。また連合艦隊でも出力できるように3行4列の画像出力、支援編成用に任意の艦隊編成を出力できるような機能が欲しいです。

既存の機能である「編成記録」で編成と装備一覧を画像出力できなくはないのですが、ステータス表示がないのと「12.7cm連装砲B型改四 (戦時改修)＋高射装置」のような長い装備名が途中で見切れてしまいます。
また編成記録に機能を追加して実現する場合、出力される画像が荒いためできれば解像度を上げていただけると有り難いです。

これはあると便利ですが、戦闘ログから自艦隊の編成を出力ができますでしょうか？

### 艦隊編成のシミュレーション分析がしたい
艦隊編成のデッキビルダー形式出力できる機能が欲しいです。

> 追伸　
マンスリー遠征のA4 南西方面連絡線哨戒の条件が
「最低5隻。軽1隻、駆2隻、他2隻必要」なのに航海日誌の条件の一つが「軽巡１駆逐４　または　護衛空母１駆逐４」となっているため軽巡１駆逐３水母２で遠征を大成功させたのに警告がでます

**Comment by Sdk0815** [comment]
@mujo4920 ご要望を上げていただきありがとうございます。

一つ目の件は率直に言って技術的になかなか難しいところが多いです。例えば長い装備名が見切れるという件に関しては実際艦これ自体でもほとんどの画面で見切れているのと同様、長い名前を表示できるように領域を広く取ると短い名前の場合には余白ができることになりますし、複数行にわたるとレイアウトが崩れるなどです。ですがそのようなご要望はあると思いますのでもちろん検討はしてみるのですが、もしこんな画面だったらうまくできそうというようなアイディアがあれば是非お知らせください。

二つ目の件は[こちらのサイト](http://kancolle-calc.net/deckbuilder.html)等で表示するためのデータを出力したいというご要望であってますでしょうか？であれば対応可能だと思いますので実装を検討します。

追伸の遠征条件の件は確認して必要に応じて修正します。報告ありがとうございます。この手の条件は実装した当初ははっきりわかっていないまま実装した場合などもあり適宜更新しなければならないのですが、なにぶん数が多いので確認漏れはどうしても生じてしまいます。おかしなところに気づいた場合は遠慮なくお知らせください。

よろしくお願いいたします。

**Comment by mujo4920** [comment]
たしかに長い名前は現状の艦これ画面でもそのまま省略されているので仕方がないかもしれませんね。編成画像を見たときにひと目で艦これプレイヤーが理解できるためには、実際のゲーム画面に近い編成画像が良いかもしれませんね。

現状、自分が編成画像を出力するのに使っているのが「艦これ一覧めいかー改二」を使って以下のように画像出力しています。
![攻略編成_20200716-004549281](https://user-images.githubusercontent.com/68387034/87798309-cdac1080-c886-11ea-976a-cd3767e7e79e.png)
このツールですと艦これ画面を直接撮影するので、必要なステータスと装備は確認できるのですが**補強増設の改修値**が表示されないため正確な情報が読み取れないのです。

ですので既存のツールで理想のレイアウトとしては

**図　きぃのんさんのツイッターより**
![きぃのんのツイッターより](https://pbs.twimg.com/media/EdCVa-VVcAATJyo?format=png&name=large)

がすべての要件を満たしてるレイアウトかと思います。おそらく[七四式電子観測儀](https://github.com/andanteyk/ElectronicObserver/wiki/FleetImageGenerator)の編成画像出力だと思いますがこれですとステータスと装備、および改修値がすべて表示されているため理想のレイアウトかと思います。

デッキビルダー形式に関しましては
[作戦室 Jervis OR](https://kcjervis.github.io/jervis/)
[制空権シミュレータ](https://noro6.github.io/kcTools/)
で分析シミュレーションをしたいためですが、提示されたサイトと同じ出力のはずです。

デッキビルダー形式で出力が可能ということですが、それをもとに用意したレイアウトに流し込み編成画像を出力ということができるのでしょうか？

以上ご検討お願いいたします

**Comment by Sdk0815** [comment]
@mujo4920 詳細な返答ありがとうございます。デッキビルダー形式については、（試したわけではありませんので実装したら違う形になるかもしれませんが、）イメージとしては所有艦娘で艦娘を選択して右クリック等でメニューを選ぶと、そのサイトに入力するためのテキストをクリップボードにコピーしたり、あるいは直接そのサイトを開いたりすることも可能ではないかと思っています。

私は各種デッキビルダーのサービスにそこまで詳しくないのですが、その入力を受け付けたら編成画像を生成してくれるサービスがあれば logbook-kai で実装しなくてもよいことにはなりますね。編成画像については前に書いたように技術的にもデザイン的にもかなりの労力を要するので、まずはデッキビルダー出力のほうから検討したいと思います。

よろしくお願いします。

**Comment by mujo4920** [comment]
@Sdk0815 返信ありがとうございます

デッキビルダー形式は艦隊単位で出力したほうが良いかと思います。というのはデッキビルダー形式を反映する入力場所が艦娘ごとではなく全艦隊を対象としてるため第4艦隊までまとめて入力できるようになってると思います。なので第1艦隊と第2艦隊まとめてや、第1艦隊だけなどの艦隊形式でのUIにしたほうが良いのかと思われます。

艦隊編成画像の出力に関しましては労力がかかるなら仕方ないですね。

これはライセンス的にOKなのかわからないんですが、そもそも七四式という完成された編成画像出力があるのならばそこからソースコードをお借りして実現させるという方法もありなのでしょうか？
あちらも The MIT License (MIT) なので、もしできるならデザイン部分はこれで解決するのではと思った次第です。

**Comment by Sdk0815** [comment]
@mujo4920 なるほど。艦娘一覧には艦隊ごとのタブがあるので
![image](https://user-images.githubusercontent.com/3181895/87872301-2fd55480-c9f2-11ea-9458-4f86b5f707a8.png)
ここから選べばよいかなと思ったのですが、これだと艦の順番もソート順に依存しているので望み通りの出力にならないかもしれないですね。どう出力するのが良いか考えてみます。別UI（ダイアログ等）がいるかもしれないですね。

ほかのソフトウェアからコードをお借りする（コピーする）のはライセンス的には可能かもしれませんが、倫理的（？）にはちょっと躊躇しますかね。そもそも七四式さんは確か C# という（logbook-kai の Java ではない）別の言語を使って書かれているのでそのまま拝借することはできないです。

私もお金をいただいて仕事として作業しているわけではないので、いろんなものをすべてご要望通りに迅速に実装できるわけではないことはご了承ください。できるものから少しずつ、今回の場合はデッキビルダーの出力から取り掛かれたらと思います。

**Comment by downyohn** [comment]
デッキビルダー形式よりも艦隊分析さん[https://kancolle-fleetanalysis.web.app/#](url)の**JSON出力**に対応をリクエストします。
装備の方は出力対応しているのでそれに合わせる形になりますね。

それとデッキビルダー形式の出力は外部サイトの出力に任せればと思います。

補強増設の改修値の件は「艦これ一覧めいかー改二」さんのreadmeか何かに記載があったのですが、編成画面→各艦娘の詳細からキャプチャしていけば改修値も表示できるますね。

**Comment by mujo4920** [comment]
@downyohn さんありがとうございます
艦これ一覧めいかー改二での改修値の表示、無事に確認できました。なんでこんなかんたんなことに気づかんかったんだろ

![攻略編成_20200727-175906359](https://user-images.githubusercontent.com/68387034/88524563-751e0580-d034-11ea-9a56-1179f0c9836f.png)

**Comment by Sdk0815** [comment]
@downyohn コメントありがとうございます。艦隊分析さんのほうは簡単なので（全艦娘の情報を出力すればいいため）、恐らく近いうちにサポートできると思います。

@mujo4920 デッキビルダー形式のほうもある程度めどがつきました。データをクリップボードにコピーできるようにしますので、利用したいサイトのページにペーストして読み込めるようにします。艦隊シミュレーター＆デッキビルダーさんと作戦室 Jervis OR さんで読み込めそうなところまでは確認しました。こちらはもう少し変更が必要なので次のバージョンに間に合うかはわからないですが、実装を進めていく予定です。

（画像出力のほうは解決されたようでよかったです。）

**Comment by downyohn** [comment]
@Sdk0815  対応ありがとうございます、期待しております。

@mujo4920 詳細からなので一手間かかってしまいますね、これで解決かな。

**Comment by Sdk0815** [comment]
@mujo4920 @downyohn すぐ上に出ていますように、艦隊分析さんへの所有艦娘・所有装備（実装済み）の登録用データの生成、及びデッキビルダー系（艦隊シミュレータ＆デッキビルダーさん、作戦室 Jervis ORさん、制空権シミュレータさんで動作確認済み）への艦隊情報及び基地航空隊の登録用データの生成、両方とも実装が完了しました。どちらもクリップボードにデータをコピーするので、それぞれのサイトの入力欄にコピーして適用してもらうやり方になります。

もう少しテストを経て問題なければ次のバージョンで利用可能になります。次のバージョンのリリースまで今しばらくお待ちください。

**Comment by Sdk0815** [comment]
@mujo4920 @downyohn 上記の対応が `v20.8.1` で取り込まれましたのでご確認ください。よろしくお願いします。
