### ISSUE TITLE
【要望】メイン画面(+所有艦娘一覧)におけるコンディション値の強調

### ISSUE THREAD

**Issue by naoto-seki** [sanaehirotaka/logbook-kai#198]
### 機能拡張で解決したい課題
現状メイン画面で見えるコンディション値は文字色だけで区別されていますが、パッと見がわかりにくいと個人的に感じています。
背景色や文字のボールドによって変化を付けて見やすくしたいです。
※とくにキラキラの方、疲労は現状でもわかりやすい。

### 実装してほしい機能について
コンディション値を下記のように区分けそれぞれ強調表示を行う。
赤疲労 00-19： 赤字 赤背景
疲労 20-29： オレンジ字 黄色背景
通常 30-49： 装飾なし
ちょいキラ 50-53：緑文字
キラキラ 54-100：緑文字 緑背景 ボールド

※「30-39」「40-49」「54-82」「83-100」でも区切りたい気はしないでもないがそこまではいらない気がする、どうだろう…

### その他
個人的運用ですがmain.cssの50行目くらいからを下記のように書き換えて対応しています。
※見え方は添付画像参照。コメントは自分用のメモなので無視してください。

![image](https://user-images.githubusercontent.com/38062567/87756326-b1d34b00-c843-11ea-8b14-1af07459bcbd.png)

```/* キラキラ(-53) */
.deepgreen { /* ? */
    -fx-text-fill: rgb(0, 128, 0);
}
.green { /* キラキラ(54-100) */
    -fx-text-fill: rgb(0, 128, 0);
    -fx-font-weight: bold;
    -fx-background-color: rgb(200, 255, 200);
}
.orange { /* 疲労 */
    -fx-text-fill: rgb(255, 140, 0);
    -fx-background-color: rgb(255, 255, 200);
}
.red { /* 赤疲労 */
    -fx-text-fill: rgb(255, 16, 0);
    -fx-background-color: rgb(255, 200, 200);
}```

**Comment by Sdk0815** [comment]
@naoto-seki ありがとうございます。色の設定をオプションにできるかなど、実装方法の検討を行います。

**Comment by Sdk0815** [comment]
@naoto-seki いろいろ検討してみましたが、オプションにするほど好みが分かれるものでもなさそうなので、ほぼご提案の通りのイメージで実装しようと思います。

![image](https://user-images.githubusercontent.com/3181895/88188002-35d96880-cc72-11ea-80cc-fbd6a441cc53.png)

統一感を持たせるために以下のようなルールにしました。
- 状態分けは従来通り 0-19, 20-29, 30-49, 50-52, 53-100
- 二段キラ(53以上)と疲労(29以下)は通常状態とは違うということでboldにし、背景色をつける
- 背景色は文字色と同じでアルファ(透明度)0.1で調整する

一段キラ状態の緑（50-52）はほとんど黒と区別がつかなかったので二段キラと同じ色（0, 160, 0）にして、二段かどうかは装飾（bold + 背景色）で区別するようにしました。これは艦これのUI上は50-52と53以上は区別がつかないことを少し意識した設計になっています。

**Comment by Sdk0815** [comment]
マージしました。次のバージョンから利用可能です。
