### ISSUE TITLE
【要望】HPバーと経験値バーの背景色を白抜きにしてもらいたい

### ISSUE THREAD

**Issue by kabotya777** [sanaehirotaka/logbook-kai#200]
■機能拡張で解決したい課題
HPバーは緑色、経験値バーは水色で表示されており、背景色が灰色となっていると思います。
個人的に、背景色が灰色であるとどの程度HPが減ったのか見辛いです。

■実装してほしい機能について
背景色を白色に変更していただけると大変助かります。

■その他
イメージは下記のような感じです。
上3人の背景色を白抜きにしています。こうなるとだいぶ見やすくなるのではないかなと思っています。
![ex](https://user-images.githubusercontent.com/68454665/87844426-e43e8000-c8f7-11ea-8e7a-0ab5f9e703de.png)

＃とはいえ、見え方は人それぞれであるとは思うので、一度検討していただければと思います。

**Comment by Sdk0815** [comment]
@kabotya777 ありがとうございます。そうですね、確かに私も白抜きのほうが見やすいように思いますし実装も比較的容易だと思いますが、少しみなさんの意見を聞いたりなど実装方法は検討してみたいと思います。

**Comment by kabotya777** [comment]
@Sdk0815 ご確認ありがとうございます。皆さんの意見も聞いてみて判断してもらえばと思います。特に急ぎというわけでもないので、手隙のときに検討していただければなと！よろしくおねがいします。

**Comment by Sdk0815** [comment]
@kabotya777 ご存じの通り今ツイッターのアンケートで意見を集めているのですが、途中の段階ではかなり綺麗に割れてしまっています。やはりみなさん好みが分かれそうですね。

一つ気づいたのは現在のゲージの背景色ってグレーなわけじゃないのです。正確には透明度が40%（40%背景を透かす）の「白」でした。そこでよく艦娘のバナー（艦隊のタブで表示している艦娘の画像）を見てみると、ちょうど経験値のバーが重なっている部分って右端のほうにかけて黒い線が入っているんですよね。↓この部分です。

![image](https://user-images.githubusercontent.com/3181895/87998931-53081d00-cb34-11ea-9cf2-45dfd6194d70.png)

それが透明度0.6で表示したときに右に行けば行くほどグレーな感じが強くなり、かつ背景の模様が一様じゃないため見難さを感じる原因になるのかもと思いました。

ですので、もしこのまま割れるようでしたら、透明度をもっと下げると今の色の感じをあまり変えずに見やすくなるのかなとも思っております。
![image](https://user-images.githubusercontent.com/3181895/87999251-34565600-cb35-11ea-9ccc-9b3291cd3532.png)
（これは透明度10%の青みがかった薄いグレーです。）

**Comment by kabotya777** [comment]
@Sdk0815 Twitterのアンケートありがとうございます！私の方でも確認しましたが、だいぶ意見分かれましたね。確かに現状の色合いのほうが全体の雰囲気としては合っているようにも思います。

よくよく見てみると、グレーではなく透明度設定されていたんですね。画像添付してもらった透明度10％のバージョンですが、とても良いと思います！これまでの雰囲気保ちつつ、だいぶ色合い的に見易くなった感じですね！

**Comment by Sdk0815** [comment]
ほぼ上記のような色合いに変更しました（ほぼ、というのはレベル99, 175の艦娘についてはゲージを表示しない変更も入れました）。次のバージョンでご確認ください。

**Comment by kabotya777** [comment]
@Sdk0815 
本件、ご対応ありがとうございました。ご連絡おそくなりましたが、先程アップデートを行い実装確認しました！かなり見易くなったと思います◎今後も末永く利用させていただこうと思います。ありがとうございました！

**Comment by Sdk0815** [comment]
@kabotya777 確認ありがとうございました。今後も何かありましたら遠慮なく issue をあげておしらせください！よろしくお願いします。
