### ISSUE TITLE
所有艦娘の火力(素)の値が装備によって変化する

### ISSUE THREAD

**Issue by azhe6526** [sanaehirotaka/logbook-kai#201]
### 問題概要
所有艦娘の火力(素)の値は何も装備していない火力を示すべきところで、火力上昇効果がある装備を装備すると、火力(素)の値も変化してしまう。

### 再現方法
陽炎改二(火力改修Max)を使った例を示します。
1. 艦これ上で何も装備していない状態の陽炎改二の火力を確認する: 68
2. 航海日誌で所有艦娘を開き、陽炎改二の火力(素)の値が68であることを確認する
3. 艦これ上で12.7cm連装砲C型改二(未改修)を1本装備する(火力上昇効果で追加で火力+2)
4. 航海日誌の所有艦娘上で陽炎改二の火力(素)の値を確認すると68ではなく70になっている

### 本来予想される動作
上記の再現方法で言えば、火力(素)は艦娘が何も装備していない状態の火力を示すべきなので、装備にかかわらず火力(素)は68

### 動作環境
 - OS: Windows10
 - Java: Java SE Runtime Environment 1.8.0_201
 - 航海日誌Version: 20.7.6

**Comment by Sdk0815** [comment]
@azhe6526 報告ありがとうございます。詳細は見てみないとわからないですが、確かAPIでは装備後の火力しか取れなくて、装備自体の火力を引くことで素の火力を計算しており、かつ艦娘のフィットやシナジーでの増分はAPIの結果からではわからなかったように思います。なので修正可能かどうかも現時点では不明ですが、何とか対応できないか調査してみます。

**Comment by azhe6526** [comment]
APIが返してくる値をそのままセットしているとなると、修正は難しいかもしれないですね…
素の火力や素の索敵でソートできるところがこのツールの大きな魅力の1つでして、テスト版の評価等、協力できることはなんでもいたしますので、遠慮なく行っていただければと存じます。

**Comment by Sdk0815** [comment]
ありがとうございます。確か近代化改修できる項目（火力・雷装・対空・装甲、あと多分運とHPも）については改修で上がった値が取れたような気がするので、もともと定義されている艦娘ごとの素の値と組み合わせればできるかもしれないと思ってます。それ以外、例えば対潜や回避はレベルで値が違うのでそう簡単にいかないかもしれません。

いずれにせよ調査が必要なのでもう少しお時間をいただければと思います。よろしくお願いします。

**Comment by Sdk0815** [comment]
現状の調査結果です。やはり火力・雷装・対空・装甲、運、耐久（（素）は表示していませんが）については上記の方法で計算できそうです。対潜、索敵、回避についてはレベル99であればわかりますが、それ以外のレベルの場合は今のところまだ計算方法が（可能なのかも含め）わかっていません。もう少し調査を継続しますが、わからない場合はこの３つについてはレベル99のときのみ正確な算出方法でそれ以外のレベルの場合は従来通りとするか、もしくは素の値の行をなくすかのどちらかになりそうです。

**Comment by azhe6526** [comment]
調査いただきありがとうございます。装備をはずすことで一応問題の回避はできるので、調査の結果わからなかった場合は特に対潜、索敵の素の値の行はなくさない方向としていただければ幸いです。

**Comment by Sdk0815** [comment]
@azhe6526 いろいろ調査してみましたが、対潜・索敵・回避についてはやはり送られてくるデータだけではわからないようです。そこで次善の策として、現在実装済みの艦についてはこれらの最小値（レベル1のときの値）をデータとして事前に与えておくことでおそらく正確に計算できるものと考えています（wiki などに記載があります）。もちろんその定義ファイルは随時更新していく必要がありますが、ずれるのがその定義ファイルにまだ定義されていない艦のみとなるので、ずれるケースはかなり抑えられるのではないかと思います。

ですので、実装方針としては
- 火力・雷装・対空・装甲、運：艦これ側の定義ファイルを用いて、近代化改修分を加えて素の値を計算する（全艦）
- 対潜・索敵・回避： logbook-kai に登録済みのデータを使って値を計算し（（Lv99時の値 - Lv1時の値) x Lv/99 + Lv1時の値）、それに（対潜のみ）近代化改修分を加える （登録済みの艦のみ、未登録の艦は従来通りの計算）

としようと思います。実装はほぼできていますので、恐らく次のバージョンでは修正できると思います。

**Comment by azhe6526** [comment]
御対応いただきありがとうございます。対潜・索敵・回避の値がずれるのは定義ファイルに定義されていない新艦のみとのことで、新艦も含めて素の値でソートして比較する状況は考えにくいので、メンテナンスするファイルが増えてしまって恐縮ですが、素晴らしい解決策かと存じます。言い出しっぺということで、新艦実装時には定義ファイルの更新等で貢献できればと考えております。次のバージョンを楽しみにしております。

**Comment by Sdk0815** [comment]
ありがとうございます。その時はよろしくお願いします。

実装を試してみましたところ、いろいろ補正が乗る熟練搭乗員を夕立改二に搭載し
![image](https://user-images.githubusercontent.com/3181895/88081723-c143f280-cbbb-11ea-8f6c-d347fdac1328.png)

このような結果を得ました。
![image](https://user-images.githubusercontent.com/3181895/88081811-e59fcf00-cbbb-11ea-83fe-d92d2b712a51.png)

装備解除して確認したところ
![image](https://user-images.githubusercontent.com/3181895/88081875-fea88000-cbbb-11ea-88fc-90cdc5ce4a92.png)

となりましたので、火力、雷装、対空、装甲、運、そして問題の対潜、索敵、回避ともすべて一致しました。定義ファイルに間違いがあるかもしれない等細かいずれはまだあるかもしれませんが、とりあえず概ね問題なさそうです。

**Comment by Sdk0815** [comment]
マージしました。次のバージョンに取り込まれる予定です。一部（3隻ほど）まだ初期値がわかってない艦娘の情報は登録されていませんが、わかり次第更新して行きます。定義は[こちら](https://github.com/sanaehirotaka/logbook-kai/blob/master/src/main/resources/logbook/supplemental/ships.json)にありますので、もし気づかれた際にはPRで更新依頼を出していただいてももちろん構いません。よろしくお願いします。
