### ISSUE TITLE
遠征条件 44 航空装備輸送任務

### ISSUE THREAD

**Issue by skierbasser** [sanaehirotaka/logbook-kai#204]
### 問題概要
遠征条件 44 航空装備輸送任務
の編成条件は、「全6隻。空母(水母,護母可)1隻、水母1隻、軽1隻、(駆+海防)2隻、他1隻必要」です。

### 再現方法
実際、水母2隻、軽1隻、(駆+海防)2隻、他1隻でも成功しますが、
航海日誌ではこの編成では満足しないと注意メッセージが出てしまっています。

### その他
とても使い勝手の良いツールで大変感謝しております。

**Comment by Sdk0815** [comment]
@skierbasser ご報告ありがとうございます。次のバージョンで修正します。

遠征の条件は手動で追加しており遠征自体の数も多いためどうしてもこのように間違いや対応漏れが発生することがあります。今後も見つけられましたら遠慮なくお知らせください。よろしくお願いします。

**Comment by Sdk0815** [comment]
修正をマージしました。次のバージョンで修正されます。

**Comment by skierbasser** [comment]
迅速な対応ありがとうございます。
