### ISSUE TITLE
所有艦娘一覧でフィルターの一部が保存されない

### ISSUE THREAD

**Issue by headsupsevens** [sanaehirotaka/logbook-kai#210]
### 問題概要
所有艦娘一覧でフィルターを設定して、一旦閉じてからまた開くと、数値型のカラムの条件が「以上」に変わってしまいます。

### 再現方法
1. 「所有艦娘一覧」を開く
2. 数値型カラムのフィルターを設定する
    例：「Lv」「98」「等しい」を設定する
3. 「所有艦娘一覧」を閉じてから、また開く

### 本来予想される動作
数値型カラムのフィルターで「等しい」に設定したはずが、「以上」に変わってしまいます。

**Comment by Sdk0815** [comment]
@headsupsevens ご報告ありがとうございます。確認しました。修正を行います。

**Comment by headsupsevens** [comment]
対応ありがとうございました。

**Comment by Sdk0815** [comment]
修正をマージしました。次のバージョンからは直っているはずですのでリリースまでお待ちください。よろしくお願いします。
