### ISSUE TITLE
所有装備一覧のフィルターで、装備の種類を選択する方法

### ISSUE THREAD

**Issue by headsupsevens** [sanaehirotaka/logbook-kai#211]
### 機能拡張で解決したい課題
所有装備一覧のフィルターで、装備の種類を選択するには、「テキスト」をオンにしてプルダウンから選択する必要があります。
しかし、プルダウンでの選択は一覧性が低く、また目的の位置までスクロールするのが大変です。

### 実装してほしい機能について
所有艦娘一覧のように、チェックボックス方式で装備の種類を選択できるようにして欲しいです。
（ただ、種類が多いので、ある程度カテゴリ毎にまとめた方がいいのかもしれませんが）

**Comment by Sdk0815** [comment]
@headsupsevens 要望を上げていただいてありがとうございます。

文字で一部入力すれば絞り込めますが、それではやはり面倒でしょうか？

![image](https://user-images.githubusercontent.com/3181895/88492654-3e6dce00-cfe7-11ea-8562-669e9bfd78cf.png)

また、そのフィルターはカテゴリだけでなく装備名自体でもフィルター可能になっています。

![image](https://user-images.githubusercontent.com/3181895/88492696-9d334780-cfe7-11ea-8590-87cbb50847f5.png)

ですので、既存の機能を落とさずに実装するならば、別のフィルターを用意する必要がありそうです。実は装備一覧のフィルターを艦娘一覧のように実装しようかと思ったのですが、コメントしていただいているように数が相当数あるのでかなり場所を取ってしまう懸念があり、現在の実装がそのままになっています。

カテゴリごとにまとめるのはチェックボックスの相性が悪いのです。例えば、「主砲」カテゴリを選んで「小口径主砲」「中口径主砲」「大口径主砲」のチェックボックスが出たとして、そこで小口径主砲だけを選びます。次に「副砲・機銃」を選んで「機銃」を選びます。その時既に「主砲」用のチェックボックスは消えているので画面上では「機銃」のみを選んでる状態が見えてることになります。こうなるとわかりにくい＋不便なので、既に選択済みのほかのカテゴリのチェックボックスのみ残しておくとか（これは可変長となるのでUI的には作りにくいです）、もしくはチェックボックス（複数選択）はあきらめて単一選択にするか、のどちらかになりますね。

**Comment by headsupsevens** [comment]
ありがとうございます。

やはり文字入力はマウスから手を離さないといけなくて面倒なのと、種類の名称を覚えないといけないのでつらいです。
（主砲や機銃くらいなら大丈夫だと思いますが、例えば特殊潜航艇とかは覚える自信がありません・・・）

個人的には、ゲーム内で装備選択するときくらいの荒い分類でも良いのですが、機能がダウングレードしてしまいますね。

また、複数選択ではなく単一選択でも良いのですが、一つの案としてはツリー表示にして、最初は大分類だけ表示するとかは、どうでしょうか。
以下のような感じで、2～3列に分ければコンパクトに表示できるかなと思いました。

▼✅主砲
　　✅小口径主砲
　　✅中口径主砲
　　✅大口径主砲
▼🔳副砲・機銃
　　🔲副砲
　　✅対空機銃
▶🔲魚雷

**Comment by Sdk0815** [comment]
なるほど、ツリー表示は一つ選択肢としてはありですね。検討してみます。ただツリー表示って実装するのは案外面倒なので（すみません）、最低限としては大分類だけのチェックボックスとかもありかもしれないですね。

余談ですが、ゲーム内の大分類ってAPIでは確か取れなかった（恐らく艦これではクライアント側の実装でしかない）記憶があるので、艦これから大分類を取得するのは難しいかもしれないです。その場合は logbook-kai 側で定義を持つしかないですが、装備のカテゴリはそうそう増えないと思いますのでその実装方法でも可能だとは思います。

**Comment by headsupsevens** [comment]
ありがとうございます。
色々と大変そうだということは分かりました。
無理やり実装してUIが変になるのも嫌ですし、もしUI的にもしっくりくる解決策があったら、実装の検討をお願いしますというくらいの気持ちです。
よろしくお願いします。

**Comment by Sdk0815** [comment]
@headsupsevens お待たせしております。いろいろ検討した結果、こんな感じの実装で進めてみようと思っています。やはり艦種と違って数が多いので、そのフィルター部分だけを折りたためるようにして、一度セットしたら閉じれるようにしようという考えです。

![image](https://user-images.githubusercontent.com/3181895/93786500-5c178680-fc6a-11ea-88f1-c21a53039066.png)

まだフィルターとしての実装はされていないのでフィルターの選択とは違う結果が出ていますが、レイアウト的にこんな感じになりそうというお知らせです。あとこれ全体をオンオフするトグルスイッチと全選択・全解除用のチェックボックスをつける予定です。

よろしくお願いします。

**Comment by headsupsevens** [comment]
対応ありがとうございます。
やっぱりすごい量になりますね。
これまで見たことない分類がありますが、テキストフィルターの分類とは必ずしも一致してないということでしょうか。
あと、その他が多いですね＾＾；
左側が大分類なのだと思いますが、右側が複数行になると、ぱっと見で左右の対応が分かりづらいかなと思いました。

**Comment by Sdk0815** [comment]
@headsupsevens 左の大分類は艦これで装備する際に出てくるフィルターをそのまま模しています（ただ艦これでは名前ではなくアイコンなので名前をどうするかはちょっと悩みどころなんですが）。なのでその他が多いのは仕方ないですね。右は定義に存在しているものを全て出しているので、たしか未だ何も装備が実装されていないものもあるはずです。実際に実装する際には１つも装備を持ってない分類は表示しないようにしようと思います。

複数行になったときにわかりにくいのは私も同感です。可能なら左と右の（見えない）枠の上付きにして上を揃えようと思っています。それでもわかりにくいときは線を入れるなど何かできないか考えようと思います。

**Comment by Sdk0815** [comment]
少し改善してみました。これならそこそこわかりやすいかなと思います。

![image](https://user-images.githubusercontent.com/3181895/93835389-05399d80-fcba-11ea-9e1a-9961981e4b90.png)

昨日のものより変更したのは：
- 大分類の表示を上付きにした
- 大分類間の間隔を広げることで大分類の範囲をわかりやすくした
- 1つも装備を保持していない（未実装なものを含む）カテゴリは除いた
- 「すべて」を追加した

**Comment by Sdk0815** [comment]
いろいろ検討した結果、艦これの改装画面でのフィルターをそのまま模倣するとわかりにくかったので、まずは[独自のカテゴリで実装してみました](https://github.com/Sdk0815/logbook-kai/pull/9)。次のバージョンで利用可能となりますのでもう少々お待ちください。

**Comment by headsupsevens** [comment]
ありがとうございます。
前より分かりやすくなったと思います。
その他がまだ多い気がしますが、どう分類するのが良いのかは難しいですね。
ちなみに小分類の並び順は、艦これ内部で持ってるID順（実装順？）とかでしょうか？

**Comment by Sdk0815** [comment]
@headsupsevens そうですね。「その他」は確かに多いですが、それぞれの分類中にある装備の種類がそんなに多くないものばかりなのでこんなわけかたでも十分かなと思っています。実装後変えたほうがいいという意見が多いようでしたらまた検討しますね。

> ちなみに小分類の並び順は、艦これ内部で持ってるID順（実装順？）とかでしょうか？

これはその通りです。IDは大体実装順に割り振られていくようなので、おおむね実装順にならんでいると思います（余談ですが、まだ1つも装備が実装されてないものもありますので、その手の装備が今後実装されたらいきなり最初のほうに並んだりする可能性があります）。艦これの改装画面で表示される順番とも一緒ですね。例えば小口径主砲が1で中口径主砲が2なので、改装画面でもその順番で出てくると思います。

**Comment by Sdk0815** [comment]
`v20.10.1`で公開しました。よろしくお願いします。

**Comment by headsupsevens** [comment]
対応ありがとうございました。
