### ISSUE TITLE
現在の戦闘・演習で、誰がMVPが見たい

### ISSUE THREAD

**Issue by headsupsevens** [sanaehirotaka/logbook-kai#213]
### 機能拡張で解決したい課題
夜戦をするかどうかの判断材料の一つとして、その時点でのMVPが誰なのか見たいです。

### 実装してほしい機能について
現在の戦闘、現在の演習の画面のどこかに、その時点でのMVPを表示できないでしょうか。

**Comment by Sdk0815** [comment]
@headsupsevens 要望を上げていただいてありがとうございます。

再度調査してみますが、途中では確かMVPが誰なのかはわからなかったと記憶しています。というのは、ほとんどの攻撃、例えば砲撃や雷撃などでは「誰がどの艦に攻撃してダメージをいくつ与えたか」がわかるのですが、航空戦の情報は「艦隊としてどの艦にどの攻撃してダメージをいくつ与えたか」しかわからなかったような気がします。航空戦では艦これ自体が航空機を飛ばすエフェクトの後に（個別の艦の攻撃ではなく）一斉にダメージが表示される演出であるせいだと思います。MVPは全攻撃を通して最も多くダメージを与えた艦がMVPとなるので、一部わからない部分があると正確には予測できないことになります。

もしほかのツール等で実装してるなど、何かご存じでしたら調査してみますのでお知らせください。よろしくお願いします。

**Comment by headsupsevens** [comment]
ありがとうございます。
それですと、ちょっと厳しそうですね。
無理そうであれば取り下げさせていただきます。

**Comment by Sdk0815** [comment]
ご理解いただきありがとうございます。一応もう一度調査してみてから無理そうだったら close させていただきますね。

**Comment by headsupsevens** [comment]
はい。承知しました。

**Comment by Sdk0815** [comment]
@headsupsevens 念のためもう一度調査してみましたが、やはり現状艦これから送られてくるデータには航空戦で「誰が誰に攻撃したのか」の情報がないため、戦闘結果を待つ以外MVPを計算する方法はなさそうです。もちろん航空戦に参加可能な艦が1隻だけなのであれば計算できることになりますがそれでは不十分なので、今回は close とさせてください。

**Comment by headsupsevens** [comment]
はい。ありがとうございました。
