### ISSUE TITLE
現在の戦闘・演習のウィンドウ位置・サイズが共通になっている

### ISSUE THREAD

**Issue by headsupsevens** [sanaehirotaka/logbook-kai#214]
### 問題概要
保存されている現在の戦闘と現在の演習のウィンドウ位置・サイズが共通になっている。

### 再現方法
1. 「現在の戦闘」と「現在の演習」を開く
2. 「現在の戦闘」と「現在の演習」を別々の位置・サイズにする
3. 「現在の戦闘」と「現在の演習」を閉じる
4. 「現在の戦闘」と「現在の演習」を開く

### 本来予想される動作
2回目に開いたとき、「現在の戦闘」と「現在の演習」はそれぞれ最後に閉じた位置・サイズになるべきと思われますが、同じ位置・サイズで開きます。

**Comment by Sdk0815** [comment]
@headsupsevens 報告ありがとうございます。確かに（実装上区別してないので）そうなると思います。修正します。

**Comment by headsupsevens** [comment]
ありがとうございます。
ちなみに、同じウィンドウに統合することはできないでしょうか？
現在の演習の要望を出した時は、戦闘と演習のうち最後に実施されたものが（同じウィンドウ内に）表示されることを想定していました。
演習をやっているときに、現在の戦闘ウィンドウを見て、たまに出撃中と勘違いしてしまうことがありましたので、同じウィンドウ内で勝手に表示が切り替わってくれた方が嬉しいです。

**Comment by Sdk0815** [comment]
なるほど、そういうご意見もあるかもしれませんね。艦これ上では通常の戦闘と演習は明確にわかれている（異なるAPIで一部情報が異なります）ので、私は別のものとして扱う方が自然かなと思ってそのように実装しました。みなさんどう思われているかアンケート取ってみようと思います。

**Comment by Sdk0815** [comment]
@headsupsevens お待たせしました。アンケートの結果は別々のままの方が良いという意見が1.5倍ほどありましたので、その点に関しては現状のまま（別メニューで専用のウィンドウが開く）にしようと思います。

それぞれのウィンドウでの位置・サイズが共通になっている件に関しては修正を行います。よろしくお願いします。

**Comment by Sdk0815** [comment]
@headsupsevens `v20.8.1` で修正されましたのでご確認ください。よろしくお願いします。

**Comment by headsupsevens** [comment]
対応ありがとうございました。
