### ISSUE TITLE
艦隊晒しフォーマットが生成されない

### ISSUE THREAD

**Issue by mujo4920** [sanaehirotaka/logbook-kai#216]
### 問題概要
艦隊晒しのフォーマットを生成しようとして５分待っても生成されない

### 再現方法
いつのときでもフォーマットが生成されませんが以下の手順でやってもいつまでも生成されませんでした

1. 航海日誌を起動

1. 艦これを起動

1. 艦これの「GAME START」をクリックし、母港画面を表示

1. 航海日誌の「その他→艦隊さらしフォーマット」をクリック

1. 「重複した艦娘からLv1を除外する」と「重複しているロック済みの艦娘を含む」にチェックを入れる

1. 「生成」ボタンをクリック

「重複した艦娘からLv1を除外する」と「重複しているロック済みの艦娘を含む」にチェックを入れていないときでも、いつまでも待ってもフォーマットは生成せされません

### 動作環境
 - OS: Windows 10 Pro バージョン1909　OSビルド 18363.959
 - Java: バージョン8の更新261　(ビルド1.8.0_261-b12)
 - Version: 20.7.8

よろしくお願いします

**Comment by Sdk0815** [comment]
@mujo4920 ご報告ありがとうございます。すみません、私の環境ではそもそもそのメニューが出てこないのですが、それは[こちら](https://github.com/kPherox/logbook-kanmusu-list-plugin/)のプラグインを利用されているということでしょうか？であればお手数ですがそちらに報告していただければと思います。

ちなみに機能的に全く等価かどうかはわからないですが、 logbook-kai 自体にも艦隊晒しフォーマットの出力機能があります。
![image](https://user-images.githubusercontent.com/3181895/88861132-44a6b900-d238-11ea-801f-02d34adc280f.png)

**Comment by mujo4920** [comment]
@Sdk0815 
おそらくそれですね、そういえばこれプラグインで入れてたのを忘れてました。返信ありがとうございます。

またもともとの方にも機能があることが知れましたので重ねてありがとうございます
