### ISSUE TITLE
所有艦娘一覧の"対空(素)"の値が艦これ表示値と異なっている

### ISSUE THREAD

**Issue by Sorichuu** [sanaehirotaka/logbook-kai#217]
### 問題概要
所有艦娘一覧の対空(素)の値が艦これで表示される値と異なっており、他の値と見比べたところ"運"の値と同じであったため"運"を参照していると思われる。

### スクリーンショット
![Inked2020-07-30 02-59-37 796_LI](https://user-images.githubusercontent.com/68965876/88838308-4fe7ed80-d214-11ea-8daa-69768001235f.jpg)

**Comment by Sdk0815** [comment]
@Sorichuu ご報告ありがとうございます。確かに間違えていますね…。次のバージョンで修正します。
