### ISSUE TITLE
艦娘一覧の空行のcondの背景色がおかしくなる

### ISSUE THREAD

**Issue by headsupsevens** [sanaehirotaka/logbook-kai#219]
### 問題概要
所有艦娘一覧で、艦娘が居ない行（空行）のcondの背景色が緑色になったりします。

### 再現方法
1. 「所有艦娘一覧」を開く
2. フィルターを使って、艦娘が1～2人くらいになるように絞り込む
    例：「Lv」「50」「等しい」

### 本来予想される動作
艦娘が居ない行（空行）のcondの背景色は灰色になるべきと思います。

### スクリーンショット
![image](https://user-images.githubusercontent.com/34375409/88884888-72a8ef00-d272-11ea-8c4f-473acbe407f7.png)

**Comment by Sdk0815** [comment]
@headsupsevens ご報告ありがとうございます。こちらの問題は別件の修正をしていた時に偶然気が付いたので、最新のコードでは既に[修正済み](https://github.com/sanaehirotaka/logbook-kai/pull/212)ですがまだリリースされているバージョンには含まれておりません。次のバージョンで修正されますのでその際にご確認ください。

お手数をおかけして申し訳ありませんがよろしくお願いいたします。

**Comment by Sdk0815** [comment]
`v20.8.1` で修正されましたのでご確認ください。よろしくお願いします。

**Comment by headsupsevens** [comment]
確認しました。ありがとうございました。
