### ISSUE TITLE
設定ファイル破損時に正常起動しない

### ISSUE THREAD

**Issue by joniburn** [sanaehirotaka/logbook-kai#22]
起動しても艦隊情報や遠征時間等を読み込まなくなった。
ログによると、 config/logbook.bean.ShipCollection.xml が何かの拍子に破損して、ArrayIndexOutOfBoundsExceptionが発生するようになっている。

[bug_files.zip](https://github.com/sanaehirotaka/logbook-kai/files/367624/bug_files.zip)

**Comment by sanaehirotaka** [comment]
報告とPRありがとうございます

**Comment by sanaehirotaka** [comment]
一旦クローズさせていただきます。
