### ISSUE TITLE
所有艦娘一覧を開き直すとフィルターのcond と Lv のコンボボックスが初期化されている

### ISSUE THREAD

**Issue by Shadow011240** [sanaehirotaka/logbook-kai#220]
### 問題概要
所有艦娘一覧を開き直すとフィルターのcond と Lv のコンボボックスが初期化されています。

### 再現方法
1. 「所有艦娘一覧」 を開く
2. cond や Lv の条件を有効にする　※cond だけ、Lv だけ、cond とLv の両方のどれでも再現可能です
3. cond や Lv の数値を設定する
4.コンボボックスの「以上」を「等しい」など、「以上」以外の値に設定する
5.「所有艦娘一覧」 を閉じる
6.「所有艦娘一覧」 を開く
7.cond や Lv の数値は「所有艦娘一覧」 を閉じる前の数値が設定されているが、
コンボボックスは「所有艦娘一覧」 を閉じる前の値ではなく「以上」が設定されている

### 本来予想される動作
「所有艦娘一覧」で最後に設定した条件がコンボボックスも含めて設定されている

### スクリーンショット
![フィルターのコンボボックスだけ初期化される](https://user-images.githubusercontent.com/46442673/88995511-cd4f5300-d325-11ea-8ce4-705f3fcd50fc.png)
![フィルターのコンボボックスだけ初期化される_開きなおした後](https://user-images.githubusercontent.com/46442673/88995514-ce808000-d325-11ea-9787-fc8de9ebb3b8.png)

### 動作環境
 - OS:Windows10
 - Java: Java8
 - Version:logbook-kai_20.7.8

### その他
仕様通りの動きでしたら申し訳ありません。

**Comment by Sdk0815** [comment]
@Shadow011240 ご報告いただきありがとうございます。こちらの問題は #210 と同じように思われますので修正は作成済みです。次のバージョンで修正をご確認いただけますと幸いです。

余談ですが、現在の（ソースコード適用に関する）運用の仕方だと、修正を施した時点で（pull request がマージされた時点で）issue が close されるようにしていますので、この問題のように既に解決済みだけどリリースされてない問題がわかりにくいですね。少し運用方法を変えようと思います。

**Comment by Shadow011240** [comment]
ご回答ありがとうございます。
他の方がすでにご報告していた問題を確認せずに報告してしまい、申し訳ありません。
次のバージョンで確認させていただきます。

**Comment by Sdk0815** [comment]
@Shadow011240 いえいえ、本当にこちらの運用の問題でもありますので、今後も何かありましたら遠慮なく issue を上げていただければと思います。よろしくお願いします。

**Comment by Sdk0815** [comment]
@Shadow011240  `v20.8.1` で修正されましたのでご確認ください。よろしくお願いします。

**Comment by Shadow011240** [comment]
ご対応ありがとうございます。
画面で修正されていることを確認いたしました。
