### ISSUE TITLE
艦娘の画像(中・大破画像)の保存仕様

### ISSUE THREAD

**Issue by ina0024** [sanaehirotaka/logbook-kai#223]
### 問題概要
　設定→画像→保存される艦娘の画像の種類を「全て」を選択した状態で
　出撃・演習を行うと出撃した艦娘の画像が「resources\ships」配下に保存されますが、
　中・大破画像(19.png)について実際に中・大破しない場合、保存されない。
　一度、ブラウザキャッシュクリアを実施してみたが同様。

### 再現方法
　1. 画像を取得したい艦娘を艦隊に編成して任意の海域(1-1など)に出撃 or 演習実施
　2. 戦闘終了後、resources\ships 配下の対象の艦娘のフォルダを確認。
　　中・大破していない場合、19.pngの画像が保存(すでにある場合は更新)
　　されていない。

### 本来予想される動作
　出撃・演習後、resources\ships 配下の対象の艦娘のフォルダ
　に19.pngが保存（または更新）される。
　実際に中・大破している必要なし。（無傷~小破でもOK）
　※直近では4月の7周年記念の限定グラフィックも
　　この方法で画像取得していました。中・大破させる必要がないので
　　この仕様を重宝していました。
　　演習時は、相手艦隊に同一艦娘がいない状態で上記挙動であることも確認済み。

### 動作環境
 - OS: Win10 Pro 1903(18362.900)
 - Java: 1.8.0_232
 - Version:20.8.1
 -ブラウザ：Chrome 84.0.4147.105（Official Build） （64 ビット）

### その他
　本家の仕様変更、もしくは私の仕様勘違いでなければ、
　「本来予想される動作」の挙動に戻すことをご検討ください。

**Comment by Sdk0815** [comment]
@ina0024 ご報告ありがとうございます。少し調査してみないとわからないですが、そのあたりは特に変更していないので、艦これ本体側の仕様変更によるものではないかと思います。今過去の（4月にはうまくいっていたとのことなので v20.1.1 あたりでしょうか） logbook-kai を使っても過去の挙動にはならないのではないかと思うのですがいかがでしょうか？

**Comment by Sdk0815** [comment]
@ina0024 調査してみましたが、やはり画像保存関連について logbook-kai 側のコードの変更はなさそうでした。もともと logbook-kai での実装は「サーバーから `19.png` 等の画像が送られてきたらすべて保存する」という実装になっており、実際に艦これ上で表示されたかどうか（この場合は実際に中破・大破してその画像が表示されたか）については特に無関係な実装になっております。ですので、以前中破・大破していないときに中破絵が保存されていたとしたら、艦これの実装がそうなっており、その挙動が4月以降のどこかで変更された、つまり実際に中破・大破しないと送られてこないようになったのだと考えられます。

以上のことから、サーバーから送られてこない画像を logbook-kai 側で取得することは不可能ですので、当該 issue については spec であるということになります。ご期待に沿えず申し訳ありませんがご理解いただけますと幸いです。よろしくお願いします。

**Comment by ina0024** [comment]
艦これ本体側の実装が変更された可能性があること、および、logbook-kai 側のコードの変更はなさそうとのこと、承知いたしました。
logbook-kaiの本体機能とははずれたところの報告に対して
調査、およびご回答いただきましてありがとうございました。
