### ISSUE TITLE
艦載機０の時の対潜値と遠征条件確認

### ISSUE THREAD

**Issue by megarala** [sanaehirotaka/logbook-kai#225]
遠征に関して、艦載機0の時に対潜値の加算が無効になる仕様を、遠征条件確認に反映するのはさすがに難しいでしょうか？
航海日誌で通ったのに失敗で帰ってきたので調べたら、そんな仕様があったのですね…

**Comment by Sdk0815** [comment]
@megarala ご報告ありがとうございます。よくわかってないですが、例えば五十鈴改二のように艦載機0のスロットに紫雲等の対潜値がプラスになるような装備を装備した場合でも、艦これ上では艦娘のステータスで対潜値が加算されているのに遠征条件の対潜値としては加算されないということなのでしょうか？

現状は単純に艦これ上で表示されている対潜値の合計を条件の確認に使っています。艦載機数は取れるので艦載機数0のスロットに装備されている艦載機の対戦値を引くことは一応できるのですが、正確ではない可能性があります。例えば最近増えてきた、特定の艦が特定の装備をした場合に補正される値はデータとして送られて来ていないので、単純に艦載機が０の場合の装備の対潜値を引くだけでは足りない可能性がある、ということになります。

それならば逆に艦娘の素の対潜値に各装備の対潜値を足す方が安全サイドなので、そちらなら対応可能かもしれません。安全サイドというのは、素の対潜値に（艦載機なら1機以上搭載している）装備の対潜値を足す場合は、上記の補正値や熟練度・改修値の影響を受けないため実際より低く見積もられる、つまり遠征条件のほうで失敗と出ていても成功する可能性があるが、逆に成功と出ていて失敗するケースはない、ということになります。

まずは冒頭に書いた私の理解が正しいかご確認いただき、かつ正しい場合、上記の方法に計算方法を変えることについてご意見をお聞かせいただければと思います。

よろしくお願いいたします。

**Comment by megarala** [comment]
@Sdk0815
その通りです
https://wikiwiki.jp/kancolle/%E9%81%A0%E5%BE%81#about_stat
ここにもありますが、機数0の場合は艦載機の対潜値は無効となるようです。（実際に自分の遠征で確認済みです）
遠征における対潜値の扱いは複雑なようで、計算方法をどう変更すればよいかは難しいですね…
命中補正は数値に現れませんが、まさか対潜値が表示と異なるというのは考えたことがありませんでした

**Comment by Sdk0815** [comment]
@megarala なるほど、説明ありがとうございます。となりますと、やはりその細かい対潜値の計算を実装するとどうしても実際の動作とのズレが生じる危険性が高いように思います。なので私が上に書いたように、逆に低いほうに見積もる（艦娘の素の対潜値に搭載数０の艦載機を除いた装備の対潜値を加算する）実装にしたほうがよいように思いますね。「失敗」と出ているのに成功するのはそれほど問題ないと思いますが、「成功」と出ているのに失敗するのは不便だと思いますので。

**Comment by Sdk0815** [comment]
`v20.9.1` にて実装されました。ご確認ください。よろしくお願いします。
