### ISSUE TITLE
僚艦夜戦突撃発動時の現在の戦闘の詳細表示がおかしい

### ISSUE THREAD

**Issue by headsupsevens** [sanaehirotaka/logbook-kai#226]
僚艦夜戦突撃が発動した時の「現在の戦闘」画面の詳細の表示がおかしいです。
画像のように、比叡になるべきところが第1艦隊旗艦の瑞鶴になってしまっています。

![image](https://user-images.githubusercontent.com/34375409/89747504-0348c000-dafa-11ea-9f0e-e0f54ec0f4d1.png)

**Comment by Sdk0815** [comment]
@headsupsevens ご報告ありがとうございます。僚艦夜戦突撃についてはおそらく（私がメインの開発を引き継いだ時点で）まだ対応コードが実装されてないと記憶していますが（そのため「通常攻撃」と出てるのだと思います）、他方、実際に送られてきているデータについて、あたかも本隊が攻撃しているかのようなデータが送られてきていることも耳にしています。そうなると正しく表示するためには連合艦隊時に特殊対応をしなければいけないので、かつ艦これ本体側がいつか修正される可能性も考えると、対応はちょっと悩ましいところです。

ですので、本件に対してはまず僚艦夜戦突撃への対応を実装することを機能拡張として行い、その際連合艦隊の特殊対応が容易かどうかを検討します。容易であれば対応しますし、難しそうであればちょっと考えさせてください。以上の理由からタグを `bug` ではなく `enhancement` に変更させていただきます。

**Comment by Sdk0815** [comment]
特殊対応も比較的簡単でしたので対応します。なお、念のため将来艦これ側で修正されても問題なく動作するように実装しておきます。

![image](https://user-images.githubusercontent.com/3181895/90092374-bec05d00-dd63-11ea-879a-a9f5db35674c.png)

（余談ですが、Colorado の特殊攻撃にも未対応だったためついでに対応しておきます。）

**Comment by Sdk0815** [comment]
`v20.9.1` にて実装されました。ご確認ください。よろしくお願いします。

**Comment by headsupsevens** [comment]
対応ありがとうございました。
（確認はしばらくできそうにないですが、ありがとうございました）
