### ISSUE TITLE
連合艦隊第二旗艦大破時の警告音抑制のオプション

### ISSUE THREAD

**Issue by kakkou** [sanaehirotaka/logbook-kai#227]
### 機能拡張で解決したい課題
現仕様では連合艦隊第二艦隊旗艦は大破進軍しても轟沈しないといわれています。
第二旗艦大破進撃を続けているとトーストはともかく警告音が少々煩わしいです。
(自分はプレイ時に動画も残している為できれば余計なSEが入ってしまうのは抑制したいです)

### 実装してほしい機能について
自己責任によるオプション化をお願いしたいです
警告自体を完全抑制するのはあまり良くないかとも思うので第二旗艦時大破時でも
トーストは出しつつSEが鳴らないような形が良いのではないでしょうか。
(完全警告なしの設定もあっても良いかもしれませんが)

また将来的にこの仕様が是正される可能性が0とは限らない為初期値は無効であるのが望ましいと思われます。

**Comment by Sdk0815** [comment]
@kakkou ご要望ありがとうございます。検討します。

**Comment by Sdk0815** [comment]
@kakkou 実際に実装を行いながら検討してみました。警告音だけ抑制するのはちょっと中途半端な感じがあるのと、それだと２回チェックする必要がある（大破してる艦がいるかどうか、に加えて、大破している艦が第二艦隊の旗艦 **のみ** である）ことを考えると、シンプルにこちら↓の実装がよいように思います。

![image](https://user-images.githubusercontent.com/3181895/90122647-9010a980-dd98-11ea-9fce-6f1d33c30dad.png)

デフォルトはオフ（第二艦隊の旗艦であっても大破警告を行う）で実装します。よろしくお願いします。

**Comment by kakkou** [comment]
さっそくの対応ありがとうございます。

実装上の都合が良い形がよいですし目的は達成できているので問題ないと思います。

**Comment by Sdk0815** [comment]
`v20.9.1` にて実装されました。ご確認ください。よろしくお願いします。
