### ISSUE TITLE
任務進捗：戦果拡張任務！「Z作戦」前段任務

### ISSUE THREAD

**Issue by skierbasser** [sanaehirotaka/logbook-kai#232]
### 問題概要
戦果拡張任務！「Z作戦」前段任務の進捗確認で、２－４をS勝利しても達成していないことになっている。
前回のクオータリーでも同様でした。つまり毎回起きていると思われます。

### その他
クオータリー任務は複雑でどこまでやったか手動で管理するのは大変で、任務の進捗が確認できる機能は大変助かっています。

**Comment by Sdk0815** [comment]
@skierbasser ご報告ありがとうございます。今見た感じ条件が「SまたはA」ではなく「A」と指定されているためのように見えます（2-4、6-1、6-3すべて同様です。）確認してそれが原因のようでしたら対応します。よろしくお願いします。

**Comment by Sdk0815** [comment]
@skierbasser 先ほど私のところでも6-1のS勝利で進捗が進まないことが確認できたので修正を作成しました。次のバージョンに取り込まれますので今しばらくお待ちください。よろしくお願いします。

**Comment by skierbasser** [comment]
いつも迅速な対応ありがとうございます。

**Comment by Sdk0815** [comment]
@skierbasser `v20.9.2` で修正されましたのでご確認ください。よろしくお願いします。
