### ISSUE TITLE
Macで実行したときに使われるフォントの指定

### ISSUE THREAD

**Issue by azhe6526** [sanaehirotaka/logbook-kai#235]
### 機能拡張で解決したい課題
Macで実行したときに使われるフォントが汚い。

### 実装してほしい機能について
Macではメイリオではなく、Macのフォントを指定してもらいたい（例えば、ヒラギノ丸ゴシック "Hiragino Maru Gothic ProN")。

美しくないですが、src/main/java/logbook/internal/gui/InternalFXMLLoader.javaのsetGlobal()で使われている、文字の大きさを変えるコードを流用して、setGlobal()に下記のコードを追加してWIndowsとMacでcssを分ければ、WindowsとMacでそれぞれ動作することは確認しました。

        // application.cssからはフォントの指定を削除
        URL url;
        if (System.getProperty("os.name").toLowerCase().startsWith("mac")) {
            // applicatin_mac.cssでMacのフォントを指定
            url = PluginServices.getResource("logbook/gui/application_mac.css");
        } else {
            // applicatin_win.cssでは今まで通り、Meiryo UIを指定
            url = PluginServices.getResource("logbook/gui/application_win.css");
        }

        if (url != null) {
                root.getStylesheets().add(url.toString());
        }

現状
<img width="742" alt="スクリーンショット 2020-09-06 23 50 53" src="https://user-images.githubusercontent.com/59495077/92328466-ffc63b80-f09b-11ea-989d-e43276526d9c.png">

ヒラギノ丸ゴシック指定
<img width="742" alt="スクリーンショット 2020-09-06 23 49 06" src="https://user-images.githubusercontent.com/59495077/92328464-fb9a1e00-f09b-11ea-815f-342859b6f9e5.png">

**Comment by Sdk0815** [comment]
@azhe6526 ご要望いただきありがとうございます。検討してみます。

**Comment by Sdk0815** [comment]
@azhe6526 変更がマージされました。次のバージョンでは Mac では `Hiragino Maru Gothic ProN` が使用されるようになります。

**Comment by azhe6526** [comment]
御対応いただきありがとうございました。Macで指定のフォントが使用されていることを確認できました。

**Comment by Sdk0815** [comment]
@azhe6526 `v20.9.3` にて公開されましたのでクローズします。よろしくお願いいたします。
