### ISSUE TITLE
メイン画面などについての要望です。

### ISSUE THREAD

**Issue by Shadow01124** [sanaehirotaka/logbook-kai#25]
お世話になっております。

新しい航海日誌にもできれば実装してほしいと思う要望を書かせていただきました。
数が多く、申し訳ありません。

●「メイン画面」についての要望
　１．泊地修理を条件付き表示にしてほしい
　　⇒明石または明石改がどの艦隊の旗艦にもなっていない場合、非表示にしてほしい。
　２．遠征、入渠の終了予定時刻を表示してほしい
　　⇒遠征、入渠の部分にカーソルを当てたらチップが出るなど何らかの方法で、
　　　　終了予定時刻を表示してほしい。
　３．任務一覧について
　　1.表示されている任務を一括で削除する機能を追加してほしい
　　2.任務の説明文をできれば表示してほしい

●「所有艦娘一覧」についての要望
　１．リストの頭にカウントを入れてほしい
　２．艦種での指定表示機能を追加してほしい
　３．近代化改修の余地を表示してほしい
　４．次のレベルまでの必要経験値を数字で表示してほしい

●「お風呂に入りたい艦娘」についての要望
　１．自動更新してほしい
　　⇒入渠したらリストから削除したり、出撃中にダメージが入ったらリストに追加してほしい。
　２．リストの頭にカウントを入れてほしい
　　⇒人数が多くなると、数えないと何人入渠待ちなのかがわからないため。
　３．現在HP/最大HPを数字で表示してほしい
　
すでに実装済み、または開発中でしたら、大変失礼いたしました。

以上です。
よろしくお願いいたします。

**Comment by Shadow01124** [comment]
要望を聞いてくださってありがとうございます。

**Comment by sanaehirotaka** [comment]
* 「メイン画面」についての要望
  * 泊地修理を条件付き表示にしてほしい
→こちら泊地修理のカウントの仕様上条件付きにするとプリセット泊地修理で不便ですので対応予定はありません。
* 「所有艦娘一覧」についての要望
  * リストの頭にカウントを入れてほしい
* 「お風呂に入りたい艦娘」についての要望
  * リストの頭にカウントを入れてほしい
→検討しましたが使用しているツールキットの仕様上難しいまたは不可能であることが分かりました。実現できることがわかれば実装します。

他は随時実装していきます。よろしくお願いします。

**Comment by Shadow01124** [comment]
いつもお世話になっております。
ご無理を言ってしまい、申し訳ありません。
これからもよろしくお願いいたします。
