### ISSUE TITLE
母港タブ及び入渠待ちリスト等々のUIについて

### ISSUE THREAD

**Issue by ag3sbs3** [sanaehirotaka/logbook-kai#27]
いつもお世話になっております。
最近まで旧航海日誌を使っていて最近新バージョンに移行したのですが
4点程ご検討して頂きたい事項があります。

~~1.母港タブにおいて各種文字が全体的に大きく他のタブと毛色が違うものとなっており
また一覧性に欠けかねないものとなっているので文字サイズを小さく、
もしくは設定できるように出来無いでしょうか。~~

2.入居待ちリスト、所有艦娘一覧等々において艦娘のサムネが表示されるのは
視認性において良いのですが、入居待ちや所有数が多くなってきた場合
長くスクロールする必要があり一覧性に欠けかねるものとなっております。
ですのでサムネオフの設定があればそのような状況にも対応できると思います。

3.入居待ちリストと所有艦娘一覧において旧バージョンではどの艦隊に所属していたか
表示する部分がありましたが、あの表示があると同名鑑が多数ある場合
非常に便利な機能でしたので復活をお願い致します。

~~4.所有艦娘一覧において旧バージョンではグループを作成することが出来ましたが
イベント時においては作戦海域を分けるのに使用したりキラ付けの一括確認等々
これも便利な機能でしたので復活をお願い致します。~~

上記4点についてお手数お掛けしますがご一考の程よろしくお願い致します。

**Comment by ag3sbs3** [comment]
アップデートお疲れ様です。
所有艦娘一覧においてタグが導入されたので4.については取下げ致します。

**Comment by ag3sbs3** [comment]
アップデートお疲れ様です。
拡大縮小オプションの実装は嬉しい限りです。

また縮小したときに気付いたのですが，以下の症状が縮小すると顕著になるのでお手隙のときにでも修正願います。
5. ラベルが複数付いた艦娘のラベルが一行に収められる場合でも，ラベルの数分だけ上下に余白が確保されてしまう。
![img2732_20175_58](https://cloud.githubusercontent.com/assets/22286867/25702764/7aef80e8-310d-11e7-953b-bbc1e9bd2ed3.jpg)

また，#27-1. に関して私が現UIに十分慣れてしまったので取下げ致します。
ご対応中でしたら申し訳ありません。

**Comment by sanaehirotaka** [comment]
気になりますね。確認します。

**Comment by headsupsevens** [comment]
> 3.入居待ちリストと所有艦娘一覧において旧バージョンではどの艦隊に所属していたか

所有艦娘一覧で、所属艦隊の列があると嬉しいです。
例えば、第1艦隊所属なら「1」、第2艦隊所属なら「2」、どこにも所属していないなら空欄など。

遠征を出す前に、キラが付いていて、かつどの艦隊にも所属していない艦娘を探すのが面倒なので・・・

デフォルトでは非表示でもかまいません。

**Comment by headsupsevens** [comment]
対応ありがとうございました。
