### ISSUE TITLE
編成画面で他の艦隊に所属している艦娘と入れ替えると航海日誌上で反映されない

### ISSUE THREAD

**Issue by ds3ic-f** [sanaehirotaka/logbook-kai#28]
お世話になっております。

表題の件になりますが、
編成画面において、ある艦隊に所属している艦娘と、
他の艦隊に所属している艦娘を入れ替える形で編成した場合、
航海日誌上でその結果が反映されない現象を確認しました。
何度やっても動作は再現されます。
※確認バージョン：16.11.8
※v16.11.3で配布された通信ライブラリをプラグインで使用

（操作例）
前提：第1艦隊に夕立を配置、第2艦隊に時雨を配置
①編成画面に遷移する
②第1艦隊の夕立のところにある変更ボタンを押下
③リストから第2艦隊の時雨を選択
④航海日誌上で結果が反映されていない

お手数ですがご確認いただけますでしょうか。

**Comment by sanaehirotaka** [comment]
こちらで確認しましたが正しく入れ替えた結果が反映されました。
引き続き調査を行います
