### ISSUE TITLE
連合艦隊編成時に第三艦隊で出撃すると損害状況が反映されない

### ISSUE THREAD

**Issue by toro-cat** [sanaehirotaka/logbook-kai#29]
連合艦隊を編成した状態で第三艦隊でキラ付けに出撃、随伴艦が大破/中破しましたが戦闘開始時に表示が変わりませんでした。
解除して出撃した場合は正常に反映されました。
16.11.8を使用してます。

**Comment by sanaehirotaka** [comment]
v16.12.1で修正を行いました
