### ISSUE TITLE
グループエディターについて

### ISSUE THREAD

**Issue by pupuppidwu** [sanaehirotaka/logbook-kai#31]
いつもお世話になっています。

旧航海日誌にあったグループエディターの機能は、改のほうに追加のご予定はございますか？
キラキラ教徒としては、海域ごとにわけての疲労度の管理が楽だったので是非ご一考いただきたく。

**Comment by kikurinkei** [comment]
17夏イベ中、ふと思い、更新してlogbook-kaiを使い始めた者です。
まだ数日ほどしか使ってないのですが、遠征に関する時だけ旧航海日誌を立ち上げています。
その他は申し分ない出来ですばらしいです。いつもありがとうございます。

遠征で使いにくい点は、pupuppidwuさんのおっしゃることに近いです。
・旧航海日誌のグループエディターの機能がすこぶる良い点
（設定の手間がかかるが『タブ』が断然使いやすいです。ラベル管理も一つの方法で良いとは思いますが）
・新航海日誌は属してる艦隊が非表示なので、目視しにくいのです

（旧航海日誌のgroup.xmlを航海日誌改にコピペして動くのなら手書きでも作ろう。と、淡い期待をしたのですがconfigフォルダはjsonファイルだけだったので無理でした）

個人的に海戦・ドロップ報告書をエクセルに動的に読み込んで、戦果計算しています。
今月から航海日誌改に移行して、エクセルを修正して改を使い続けようと思っています。
お忙しいと思いますがなにとぞよろしくお願いします。

**Comment by kikurinkei** [comment]
バージョンアップにてラベルのタブを追加してくださりまして、真にありがとうございます。
旧航海日誌を立ち上げることは無くなりました。
旧航海日誌には長い事おせわになりました。いままでありがとうございました。

**Comment by sanaehirotaka** [comment]
こちらこそありがとうございます。
一旦クローズさせていただきます。
