### ISSUE TITLE
所有艦娘一覧の経験値表示

### ISSUE THREAD

**Issue by uzaemon** [sanaehirotaka/logbook-kai#32]
いつも航海日誌にお世話になっております。
秋イベも終わってやっと「改」を試し、その進化をとても嬉しく感じています！
主題の件ですが、以前のように艦娘一覧に経験値／Nextを表示することは可能でしょうか？
できれば項目ごとの表示・非表示が選択できるとありがたいです。
何となく艦種毎にレベルを合わせる習慣があり、前バージョンは頻繁にチェックしていました。
そのような用途なので、一覧のデフォルトソート順を指定できるとさらに助かります。
お手数とは思いますがご一考いただけると幸いです。

**Comment by sanaehirotaka** [comment]
ありがとうございます。
次のバージョンで所有艦娘一覧に経験値の項目を追加いたします。
デフォルトソート順の変更はお待ち下さい

**Comment by sanaehirotaka** [comment]
v17.5.1で「所有艦娘一覧」にNextの項目が追加されたためクローズします

**Comment by uzaemon** [comment]
ご対応有難うございます！
メンテ明けの楽しみが増えました。
