### ISSUE TITLE
キャプチャした画像が消える

### ISSUE THREAD

**Issue by MSA-i** [sanaehirotaka/logbook-kai#33]
キャプチャした画像が22枚以上になると古いものから順に消えていってしまうのですが、仕様でしょうか？

**Comment by sanaehirotaka** [comment]
はい。仕様です
最大200枚一覧に保持出来ますが、メモリが不足している場合はそれより少ない数しか保持出来なくなっています。

**Comment by sanaehirotaka** [comment]
v17.5.1で直接ファイルとして保存する機能が付いたためクローズします
