### ISSUE TITLE
遠征ログの表示

### ISSUE THREAD

**Issue by dexter-kankore** [sanaehirotaka/logbook-kai#34]
航海日誌には大変お世話になります。
遠征ログですがデイリー、ウィークリー表示ではなく
日付毎に表示されるような対応は難しいでしょうか。

遠征ログ結果のクリップボードコピーができてないようです。
以下のようになってしまいます。

資材	合計	平均
logbook.internal.gui.MissionAggregate@e70f759

日付	遠征名	結果	燃料	弾薬	鋼材	ボーキ	アイテム1	個数	アイテム2	個数
logbook.internal.gui.MissionLogDetail@517d35be

**Comment by sanaehirotaka** [comment]
報告ありがとうございます。
クリップボードにコピーが出来ない件について修正し致します。
遠征ログの集計単位については検討させて頂きます。
