### ISSUE TITLE
一覧画面のフィルターの操作改善

### ISSUE THREAD

**Issue by spineltwin** [sanaehirotaka/logbook-kai#35]
例えば装備画面でフィルターして表示しようと思った場合
フィルターをクリック
種類をクリック
コンボボックスをクリック
一覧から選択
の4操作が必要になります。
このフィルター設定は記憶されないので開くたびに毎回この操作をすることになります。
一覧系の画面はすべてこのようにフィルターとオンオフクリックを
必ず行うことになっていて面倒です。

例えば、コンボボックスに[すべて]というのがあれば
コンボボックスをクリック
一覧から選択
の２操作で済みます。
ですので、フィルターと種類オンオフボタンは必要なくなります。
もしくは開閉状態とオンオフの状態を記憶してほしいです。

**Comment by headsupsevens** [comment]
> もしくは開閉状態とオンオフの状態を記憶してほしいです。

私もこの機能は欲しいです。
その場合、状態を全部をリセットするボタンなどもあった方が便利かもしれません。
