### ISSUE TITLE
疲労時の顔アイコンが表示されない

### ISSUE THREAD

**Issue by torori910** [sanaehirotaka/logbook-kai#36]
2017冬イベントの辺りまでは問題なかったのですが、
最近疲労時に付いていた赤とオレンジの顔マークのアイコンが航海日誌側に反映されなくなりました。

ブラウザのキャッシュを削除しても疲労アイコンの画像は取得されていないようです。

ブラウザの設定や環境依存の問題でしょうか？

**Comment by sanaehirotaka** [comment]
ご報告ありがとうございます。
こちらでも問題を確認しました。いつからかは不明ですがアップデートでアイコンが削除されて表示できなくなったのが原因です。
logbook-kai側でアイコンを用意して対応したいと思います。
