### ISSUE TITLE
[Windows]ハンドルリークしている

### ISSUE THREAD

**Issue by spineltwin** [sanaehirotaka/logbook-kai#37]
Windows環境(Windows 8.1)で利用しているとハンドルが徐々に増えていく。5万程度まで増えていることを確認しています。

**Comment by sanaehirotaka** [comment]
ありがとうございます
確認したところFlashデコンパイラであるFFDecライブラリが一時ファイルを大量に作っており終了時まで開放しない仕様になっていました。
オンメモリで処理するように修正します
