### ISSUE TITLE
画面キャプチャに関する要望です

### ISSUE THREAD

**Issue by lesserteramon** [sanaehirotaka/logbook-kai#42]
現在の仕様だと、連続キャプチャの場合、秒間10コマで20秒間が限界のようです。
画像の保存ダイアログで秒間のコマ数を変えられるようなUIになっていますが、値を入れても反映させることができません。もし変えられるなら方法を教えてください。
また200コマが限界だと、イベントのラストを記録しようとするには時間的に足りません。
前バージョンと同様の、即時にファイルに保存していくモードも用意していただくことはできないでしょうか。
ご検討いただけますようお願いいたします。

**Comment by sanaehirotaka** [comment]
ありがとうございます、キャプチャに直接保存のオプションをつけようと思います。
> 画像の保存ダイアログで秒間のコマ数を変えられるようなUIになっていますが、値を入れても反映させることができません。もし変えられるなら方法を教えてください。

現在の仕様として連続キャプチャの間隔は最大10/秒で変更できません。「キャプチャの保存」で指定できるfpsはファイル形式をgifにした時のアニメーションGIFのレートになります。
