### ISSUE TITLE
鈴谷改二が駆逐ハ級と表示されます

### ISSUE THREAD

**Issue by nove0756** [sanaehirotaka/logbook-kai#44]
艦隊に鈴谷改二を入れていると、「駆逐ハ級」と表示されます
マウスオーバーで装備なども確認できないようです

イベント時の疲労度確認などで使わせていただいています
もし既にご確認済であればご容赦ください

**Comment by sanaehirotaka** [comment]
「駆逐ハ級」と表示されるのは艦船のマスターデータが更新されていないことが原因です。
艦船のマスターデータはゲームスタート時に読み込まれるので通常は起こり得ない事象です。
航海日誌以外のツールを使用していませんか？
