### ISSUE TITLE
現在ボス戦かどうか表示して欲しいです

### ISSUE THREAD

**Issue by mannbou1** [sanaehirotaka/logbook-kai#47]
艦娘を戦わせている間に他のことをしていると、
夜戦に突入の是非を選択するときに現在がボス戦なのかわからなくなり
一々
戦闘ログ→デイリーをクリック
しなければ分かりません。
なのでボス戦のときはツールのその他の右などあいている場所になにかしらマーク表示をして欲しいです。

**Comment by sanaehirotaka** [comment]
v17.8.1 以前でも[コマンド]-[直近の戦闘]で戦闘の詳細を確認出来ましたがv17.8.2以降から[現在の戦闘(直近の戦闘)]で今の戦闘がボスマスかを表示するようになります
