### ISSUE TITLE
艦隊編成の表での不具合。

### ISSUE THREAD

**Issue by tom4001tb** [sanaehirotaka/logbook-kai#48]
艦隊編成の表を作ってみた所、
装備とそのアイコンが食い違っている所が多いです。
艦攻が艦爆アイコンになっていたり、魚雷が副砲アイコンになっていたり
もう大変です。
ちなみに、当方は、Vista Ultimate 32bit  グーグル･クロームにて使用させていただいております。
治ってくれるとありがたいのですが…。

Tom4001tb

**Comment by sanaehirotaka** [comment]
ご報告ありがとうございます。
v17.8.4で対応しました。
