### ISSUE TITLE
所持艦娘一覧について

### ISSUE THREAD

**Issue by visgi** [sanaehirotaka/logbook-kai#50]
いつもお世話になっておりおます。

v17.9.1 にて所持艦娘一覧に第1艦隊から第4艦隊のタブが消えましたが、タブを復活する予定はありますか？
メインウィンドウ（母港）と所持艦娘一覧ウィンドウ（第1艦隊タブ）を並べて表示して出撃していたので、以前の仕様、もしくはフィルタによる対応等、ご検討いただけますようお願いします。

**Comment by sanaehirotaka** [comment]
ありがとうございます
次のバージョンで設定からタブ表示をラベル・艦隊で選択可能にする予定です。お待ち下さい。

**Comment by visgi** [comment]
対応ありがとうございます。
