### ISSUE TITLE
17.9.1で変更された所持艦娘一覧のタブについて

### ISSUE THREAD

**Issue by yudemame** [sanaehirotaka/logbook-kai#51]
イベント時にラベル単位のタブがあればたしかに便利な面があるでしょうが、
ラベル単位でしかタブを使えないとなるとイベント時以外の通常時ではタブの意味がほとんどありません。
「艦娘にラベルを追加」で艦隊単位等のタブを作ることはできますが操作があまりに煩雑です。
艦隊単位のタブを復活していただけないでしょうか。

**Comment by sanaehirotaka** [comment]
ありがとうございます
次のバージョンで設定からタブ表示をラベル・艦隊選択可能にする予定です。お待ち下さい。

**Comment by yudemame** [comment]
要望を受け入れていただきありがとうございます。
航海日誌の所有艦娘一覧は私の艦娘管理の最重要ツールですので、わがままを言わせていただきました。

遅くなりましたが、非常に有用なツールを公開、更新されていることに御礼を申し上げます。

2017年9月5日 20:09 sanaehirotaka <notifications@github.com>:
