### ISSUE TITLE
母港タブの切り離しオプション

### ISSUE THREAD

**Issue by Sdk0815** [sanaehirotaka/logbook-kai#54]
お世話になっております。いつもありがたく使わせていただいております。

ひとつ提案なのですが、母港のタブは各艦隊のタブと違って常に見えるようにしておきたいと思うことが多いので、オプション等で母港の情報を各艦隊のタブと切り離すことは可能でしょうか。イメージはこんな感じです（開発環境で突貫でレイアウトしました）。
<img width="777" alt="2017-09-14 12 11 09" src="https://user-images.githubusercontent.com/3181895/30437649-15ec28d0-99aa-11e7-923b-5ec2561edce8.png">
実際にオプションにするとなるといろいろ面倒そうな感じはしましたが、もし可能であれば実装していただけると嬉しいです。ご検討のほどよろしくお願いいたします。

**Comment by sanaehirotaka** [comment]
有難うございます。レイアウト変更自体はそこまで難しくないですが切り替えられるオプションを付けると難しそうですね
どう実装するか考えてみます。

**Comment by Sdk0815** [comment]
実装していただきありがとうございました！
