### ISSUE TITLE
猫ったり　くるくる回る

### ISSUE THREAD

**Issue by Mitchell501** [sanaehirotaka/logbook-kai#55]
logbook-kaiを使わせていただいております。
今回航海日誌拡張版しか使っていなかったのを、ブラウザ-航海日誌拡張版-航海日誌kai-web
にしたのですが、結構猫ったり右下のローディング？（くるくる）が長い時が多くなったのですが
対処方法はありますか？
通信速度は常に同じサーバー計測で90Mbpsオーバー出ています。

windows7 64bit mem8GB

**Comment by sanaehirotaka** [comment]
こんにちは。
航海日誌で問題が出ないようであればこちらのプラグインをお試しください。
https://github.com/sanaehirotaka/logbook-kai/releases/tag/v16.11.3
こちらのプラグインはプロキシライブラリを航海日誌で使用していたものに差し替えるものになります。

**Comment by Mitchell501** [comment]
ありがとうございます、sanaehirotakaさんの方法にて解決しました<(_ _)>
