### ISSUE TITLE
v17.10.4で起動しない（不具合？）

### ISSUE THREAD

**Issue by kikurinkei** [sanaehirotaka/logbook-kai#57]
おつかれさまです。いつも利用してます。ありがとうございます。
早速ですが、いつものようにv17.10.4を上書きアップデートして、
自作のショートカットクリックしても立ち上がらず、
logbook-kai.jarをクリックしてもダメでした。
再起動しておおもとクリックしても立ち上がらず。

今は、logbook-kai_17.10.2をダウンロードしてさらに上書きして普通にプレイしてます。
win9pro/java8（64bit）
ご報告まで。

**Comment by sanaehirotaka** [comment]
ありがとうございます。
調査したいので「起動しようとした後」のログファイルを頂けますでしょうか？
※ログファイルは「logs」フォルダにあります。
ログファイルはこのIssueに直接添付して構いません

**Comment by kikurinkei** [comment]
はい。ちょっと待っててね。

**Comment by kikurinkei** [comment]
おまたせしました。
[app.log](https://github.com/sanaehirotaka/logbook-kai/files/1404269/app.log)

（ついでに最大化、最少化できないことも報告しときます。）
（なんならリモートしてもいいよ）

**Comment by sanaehirotaka** [comment]
修正しましたのでこちらのバージョンで確認ください
https://github.com/sanaehirotaka/logbook-kai/releases/tag/v17.10.5

> （ついでに最大化、最少化できないことも報告しときます。）
ログファイルを確認したところ相当に古い(2015年)Javaがインストールされているようです。Javaを最新版に更新してみてください。

**Comment by kikurinkei** [comment]
早速の更新ありがとうございます。
v17.10.5
無事起動しました。
>ついでに最大化、最少化できないことも報告しときます。
まちがいでした。最大化はできて、最少化（左下に小さく）ができなかったです。
ひとまず寝まする。明日アップデートして報告します。おやすみなさいです。

**Comment by kikurinkei** [comment]
おはようございます。
javaのバージョンをjava8u45(64-bit)からjava8u151(64-bit)にアッデートして、
OS再起動しても、右上のボタン(-)で最少化できないようですが、
（正常なら旧航海日誌のように左下に小さくなるのかな）
個人的には問題ありません。報告まで。

**Comment by sanaehirotaka** [comment]
> OS再起動しても、右上のボタン(-)で最少化できないようですが、
タスクトレイに格納する機能を差しているのであれば、この機能はlogbook-kaiにはありません。
これは使用しているUIツールキット(JavaFx)ではタスクトレイの操作ができないためです。

一旦解決ということでIssueを閉じさせていただきます。何かあれば開いてください。
よろしくお願いします。
