### ISSUE TITLE
画面スタイル：ワイドのウィンドウサイズが保持されない

### ISSUE THREAD

**Issue by Kenny-D** [sanaehirotaka/logbook-kai#58]
お疲れ様です。
航海日誌、便利に使わせていただいてます。

画面モードをスマートからワイドに変更したのですがウィンドウをワイドに合わせて大きくしても、
航海日誌を再起動するとウィンドウサイズがスマートのサイズに戻ってしまいます。
ワイド版も見やすくて便利なので対応していただけるとありがたいです。
よろしくお願いします。

**Comment by sanaehirotaka** [comment]
こんにちは。
当事象についてこちらでどうしても再現しません。
スマートとワイドはレイアウトが異なるだけで同一のプログラムで動いていますので動きが異なることは無いはずなのです。
設定ファイルが読み取り専用になったりしていませんか？
一旦クローズさせていただきます。何かあれば再度開いてください。

**Comment by Kenny-D** [comment]
イベント前後のバージョンで不具合が出なくなりました。
特に設定をいじったわけではないのが気になりますが現状は問題なく使えています。
お騒がせして申し訳ありませんでした。

2017年11月19日 15:18 sanaehirotaka <notifications@github.com>:
