### ISSUE TITLE
所有装備一覧と艦娘一覧ウィンドウが出てこない

### ISSUE THREAD

**Issue by ponzu07** [sanaehirotaka/logbook-kai#59]
原因は何ですかね？
その他のウィンドウ等は正常動作します。

**Comment by ogura-anmitu** [comment]
どうやらJava9をインストールしている環境だと開けないようです。
Java8u151での展開を確認できました。

**Comment by ponzu07** [comment]
ありがとうございます。

**Comment by GairaJr** [comment]
自分も同じく所有装備一覧と艦娘一覧ウィンドウが出てこない症状に悩まされてます
JavaはJava8u151が見つからなかったためJava8u161を使用中です

**Comment by yousgw** [comment]
自分も所有装備と艦娘と戦闘ログがみれません。そのほかはすべて見れます。現在の戦闘や遠征ログ、お風呂に入りたい艦娘などは見れます。javaは8u171を使用して開いています。java10もインストールはしています。

**Comment by sanaehirotaka** [comment]
Java8より新しいJava9以降がインストールされている場合、最後にJava8をインストールしたとしてもJava9以降が優先して使用されてしまうようです。
航海日誌では今の所Java8のみで実行することが出来ます。
