### ISSUE TITLE
【バージョンv17.11.3】過去バージョンで取得済の戦闘ログが開けない

### ISSUE THREAD

**Issue by lamunex** [sanaehirotaka/logbook-kai#60]
いつも便利に使わせていただいおり有難く思っております。
さて掲題通りのご報告となります。
当方では17.10.6->現行にて17.10.6で保存したログが現行で開けない現象が発生しています。ご確認ください。

**Comment by sanaehirotaka** [comment]
こんにちは。
11/17メンテナンス以降戦闘周りの仕様が大きく変わったためメンテナンス以前の戦闘ログは読み込むことが出来ません。
よろしくお願いします。

**Comment by lamunex** [comment]
> 11/17メンテナンス以降戦闘周りの仕様が大きく変わったためメンテナンス以前の戦闘ログは読み込むことが出来ません。
こちら少々残念ですが承知しました！
