### ISSUE TITLE
単艦退避が認識されない

### ISSUE THREAD

**Issue by faisceau** [sanaehirotaka/logbook-kai#61]
いつも便利に利用させてもらっています。
一つ気がついたので報告いたします。
バージョンは17.11.5です。

「遊撃部隊 艦隊司令部」により単艦退避を実行した際、退避した艦が大破表示のままであり、
進軍するごとに大破の警告が表示されました。
新要素ですので、まだ対応されてないだけかもしれませんが、ご確認いただけると幸いです。

**Comment by sanaehirotaka** [comment]
ありがとうございます。v17.11.6で対応しました。
