### ISSUE TITLE
キャプチャ時の周囲の余白

### ISSUE THREAD

**Issue by lesserteramon** [sanaehirotaka/logbook-kai#62]
いつも便利に使わせて貰ってます。

ふと気がついたのですが、キャプチャの範囲を手動で指定した場合でも、周囲数ピクセルの
余白は自動削除されていたと思うのですが、現在は余白が残ったままになってしまいます。
過去のキャプチャを見てみたところ、9月頭のころのは余白が削除されていました。
※イベ時しかキャプってないので、9月頭～現在までのどこでそうなったかは不明です。

ちなみに、ブラウザの表示倍率は100%ではなく120%にしています。(そのため手動)
DMMの背景色が純白じゃなくなったとかですかね？
可能なら自動での余白削除の対応をお願いします。

**Comment by sanaehirotaka** [comment]
こんにちは。こちらの現象は自分の環境では再現しませんでした。
キャプチャ範囲を手動で指定した場合の余白は白(#fff)のみトリミングされ、白以外はトリミングされません（例えばウインドウの枠の影が映り込むような場合は白では無くなるためトリミングされません）。
またご使用のブラウザは何をお使いでしょうか？

**Comment by lesserteramon** [comment]
ご回答ありがとうございます。
使用しているブラウザはChromeです。バージョンは 62.0.3202.94 です。

大きめにキャプチャして、画像の周囲の白い部分の色を確認しましたが、
保存された画像がjpegで色が変化してしまっているのかも知れませんが、
一番白く見える部分でも#FEFEFEでした。
キャプチャ取得時の実際の色がどうなっているかはわかりません。

**Comment by lesserteramon** [comment]
追加でちょっと試してみました。
IEだとちゃんと周囲の余白の除去が行われます。
Chrome限定(？)の問題のようですね。

取り合えずChromeでもキャプチャ枠を手動調整して採れますので
致命的ではないですが、ご対応いただけるとありがたいです。
