### ISSUE TITLE
資源チャート

### ISSUE THREAD

**Issue by Mitchell501** [sanaehirotaka/logbook-kai#63]
おせわになります
17.10.6まで普通に資源チャートが見られていたのですが、17.11.5に更新しましたら資源チャートだけが見られなくなりました。
各CSVファイルとbattlelog・logs・configフォルダをダウンロードした最新の航海日誌kaiのフォルダにコピーして行く形をとっていますが、私の環境だとは思いますが艦これをしているPCではチャートが見られなくなり、試しに他のPCにクリーンな航海日誌kaiに資材ログだけをコピーし見たところ普通に見られました。
この二つのPCでは行っている作業が違いすぎるので何がどう影響をしているのかが分かりません。
CSVファイルはエクセルで普通に見られ、FAQの通りにもしましたがチャートに反映されません、どうしたら良いでしょうか？
javaは64bit 32bit共に11/23現在最新を入れています

**Comment by sanaehirotaka** [comment]
こんにちは。
資材チャートで読み込まれるcsvファイルは[設定]-[報告書の保存先]で指定された場所の「資材ログ.csv」を読み込みます。
[報告書の保存先]で指定された場所に「資材ログ.csv」が存在するかをご確認ください。

**Comment by Mitchell501** [comment]
こんばんは
遅くなりましたが、読み込ませる事が出来ました。
すごく初歩的な事でした、すいません。
読み込まないのでバージョンを色々変えて試したのがいけませんでした
