### ISSUE TITLE
所有艦娘一覧で「ラベルを除去」できないケースがある

### ISSUE THREAD

**Issue by cereby** [sanaehirotaka/logbook-kai#65]
細かい話で恐縮ですが、以下の手順では「ラベルを除去」できません。

(1) [所有艦娘]ボタンを押して、所有艦娘一覧ウィンドウを開く。
(2) 任意の艦娘の(行選択せずに)既存のラベル部を右クリックして、
　 コンテキストメニューから「艦娘からラベルを除去」を選ぶ。
(3) ドロップダウンリストにラベル名称が表示されないため、
　[OK]ボタンを押してもラベルを除去できない。

ラベルオブジェクトを右クリックした際に、
コンテキストメニューを表示しないようにするか、
艦娘行のコンテキストハンドラーに処理を振り替える方が、
Windows UIの作法として自然ではないかと思います。ご検討ください。

**Comment by sanaehirotaka** [comment]
ありがとうございます。
テーブル行自体にコンテキストメニューを関連付けることは簡単ではなかったため
v18.1.1でラベル操作のダイアログで対象になる艦娘の名前を表示するようにいたしました。

**Comment by cereby** [comment]
工夫して頂き、ありがとうございました。
