### ISSUE TITLE
猫が出ないエラーが頻発します

### ISSUE THREAD

**Issue by tamokiti** [sanaehirotaka/logbook-kai#68]
航海日誌（改）を使わせていただいておりお世話にっております。

ログイン時のぷかぷか丸（？）から先に進まなかったり、母港などで右下のぐるぐるが終わらない、止まるなどでします。

環境はwin10でChromeを使用しております。

個人の問題かもしれませんが、よろしくお願いします。

**Comment by sanaehirotaka** [comment]
こんにちは。
こちらのプラグインをお試しください。
https://github.com/sanaehirotaka/logbook-kai/releases/tag/v16.11.3
こちらのプラグインは別のベンダーが提供するプロキシライブラリへ差し替えるものになります。
(logbook-kaiでは標準でNettyをプロキシとして採用していますがこのプラグインによりJettyをプロキシとして使用するようになります)

**Comment by tamokiti** [comment]
迅速な対応ありがとうございます
快適に読み込むようになりました、ありがとうございます。
ただ、たまに読み込みが引っかかる（？）ようなことがありますが、しばらく様子見をしたいとおもいます。

**Comment by SSW-SCIENTIFIC** [comment]
ver16.11.2からしばらくは問題ありませんでしたがver17.12.0前後を境に通信エラーが頻発するようになった感があります(手元ではプラグイン差し替え済み)
