### ISSUE TITLE
ユーザースクリプト機能の復活を希望

### ISSUE THREAD

**Issue by momidi** [sanaehirotaka/logbook-kai#69]
いつも便利に使わせていただいております。

さて、タイトルの通り旧航海日誌に実装されていたユーザースクリプト機能(JavaScript)の復活を希望いたします。
ちょっとしたデータ統計を取ったりする際に、便利に使っていたものでして…。

本体機能ではなくプラグイン実装でも構いませんので、再度使えるようにならないでしょうか…。
ご検討をお願いいたします。

**Comment by sanaehirotaka** [comment]
こんにちは。一先ずプラグインとして実装してみました。
https://github.com/sanaehirotaka/logbook-script-loader
旧航海日誌とは実装が異なるためスクリプトには互換性がありませんのでご注意ください。
不具合や使いにくい点ありましたらご連絡ください。

**Comment by momidi** [comment]
ご対応ありがとうございます。
試用してみます。

**Comment by momidi** [comment]
試用してみました。

手持ちのスクリプト(サンプルの提督経験値表示の応用形)はメソッドの置換など書き換えは必要でしたが、
ほぼほぼ流用で動かすことが出来ました。

今のところ不具合はありません。

**Comment by momidi** [comment]
こんばんは。
いつも便利に航海日誌を利用させて貰っております。

さて、先日実装していただいたスクリプト実行機能(本当に助かります)なのですが、
最近になって、機能的には問題ないもののちょっと不便なことになっています。
コンソールに画像取得関連？の警告メッセージログが大量に流れてしまい、
スクリプトによる表示が流れてしまうのです。

警告がよく出るようになったのは画像取得オプションを追加されたあたりからだと記憶しております。
ご対処いただけないでしょうか？

ご参考までにログ画像を添付します。
![2018-08-07 02 51 13](https://user-images.githubusercontent.com/34963259/43732504-d981762c-99ec-11e8-976c-a94614e320af.png)

**Comment by momidi** [comment]
すみません、自己解決しました。
どうやら、バックアップの為にDropBox上にフォルダを置いてあったことで、アクセス競合が起きていたようです。Resourceフォルダを同期除外することで警告は出なくなりました。
お騒がせしました。
