### ISSUE TITLE
要望を2点ほど

### ISSUE THREAD

**Issue by maroncoro** [sanaehirotaka/logbook-kai#70]
いつも使わせていただいております。
遠征条件確認で新たに実装された「敵泊地強襲反撃作戦」の対応はまだでしょうか。
もう一つは所有艦娘一覧で遠征中であるかないかを確かめるフィルター機能があればいいなと思います。

**Comment by sanaehirotaka** [comment]
ありがとうございます。
v18.1.1で対応いたしました。ご確認ください。
