### ISSUE TITLE
説明が足りなかったみたいです

### ISSUE THREAD

**Issue by maroncoro** [sanaehirotaka/logbook-kai#71]
前回遠征中のフィルタを付けてほしいと要望した者です。
要望に対応して頂いてありがとうございます。
ただ、説明不足だったようで「遠征中を除く」というフィルターも
付けてほしかったです。
申し訳ありません。

**Comment by headsupsevens** [comment]
「遠征」をオンにして「遠征中」のチェックを外せば、遠征中の艦娘を除いた一覧になるようですよ。

**Comment by sanaehirotaka** [comment]
ありがとうございます。既にコメントされていますが「遠征」のフィルターを有効にした状態で「遠征中」のチェックを外していただくことで「遠征中を除く」事ができます。
