### ISSUE TITLE
艦娘画像の無効化機能の要望

### ISSUE THREAD

**Issue by tyaat** [sanaehirotaka/logbook-kai#72]
ストレージの小さい格安タブレットで利用させて頂いてるのですが、
画像のキャッシュが1GB程度まで膨らみ、ストレージを圧迫してる状況です。

そこで艦娘の画像の取得を設定からon,off可能にして頂けないでしょうか。
恩恵を受けられる人は殆ど居ないと思いますが実装を検討して頂けると幸いです。

**Comment by sanaehirotaka** [comment]
こんにちは。
艦娘の画像がストレージを圧迫している件について次の対応を考えています。
 - 使用している「1.(png|jpg)」、「3.(png|jpg)」**以外**の画像を取得しない・削除する。
   - これだけでおよそ100MB未満のサイズになります。
 - 上記に加え画像ファイルの再圧縮
   - およそ15MB未満のサイズになります。
合計15MB程度であれば許容できるかと考えています。何かあればコメントお願いします。
また、艦娘の画像ファイルは「resources」フォルダの「ships」フォルダにあり対応を待たずとも手動でも削除や再圧縮可能です。(使用していない画像ファイルを削除することによる悪影響はありません)。
