### ISSUE TITLE
現在の戦闘に関する要望

### ISSUE THREAD

**Issue by headsupsevens** [sanaehirotaka/logbook-kai#73]
自動更新の対応ありがとうございました。
追加の要望なのですが、
・戦闘中じゃなくても、現在の戦闘ウィンドウを開きたい
・戦闘の判定（S / A / B / C / D）を見たい（最終結果だけでなく途中の判定も）
・演習の結果も見たい
です。
よろしくお願いします。

**Comment by headsupsevens** [comment]
あと、現在の戦闘ウィンドウでは、退避した艦娘に「退避」の文字が付かないようです。

**Comment by headsupsevens** [comment]
「夜戦（友軍艦隊）」で敵艦が受けたダメージが、その次の「夜戦」になると消えてしまい
敵艦のHPが戻ってしまっているようです

**Comment by sanaehirotaka** [comment]
こんにちは
v18.2.6で修正したつもりなのですが最新のv18.2.6でも友軍艦隊のダメージ計算が反映されませんか？

**Comment by headsupsevens** [comment]
すみません、バージョン確認したところ、v18.2.5でしたので、友軍艦隊については取り下げさせてください。
お手数おかけしました。

**Comment by headsupsevens** [comment]
１つ目と２つ目の要望の実装していただきありがとうございました。

**Comment by Sdk0815** [comment]
3つ目のご要望（演習の結果も見たい）について対応を検討します。

**Comment by headsupsevens** [comment]
ありがとうございます。
開発引き継がれたんですね、気付きませんでした。

**Comment by Sdk0815** [comment]
そうですね、私も長らく（大規模改装前の logbook の頃から）ありがたく使わせいていただいていたので、せっかくの素晴らしいツールがメンテされずにすたれていくのはもったいないと思いまして、微力ながらお手伝いさせていただいております。

今後ともよろしくお願いいたします。

**Comment by Sdk0815** [comment]
一番直近の演習のみとなりますが、「現在の戦闘」と同様のフォーマットで演習の詳細が見れるようになる変更を入れました。次のバージョンから利用可能となります。

**Comment by headsupsevens** [comment]
対応ありがとうございました。
