### ISSUE TITLE
所有艦娘一覧のCSV出力時不具合

### ISSUE THREAD

**Issue by momidi** [sanaehirotaka/logbook-kai#75]
首記の通り、「所有艦娘一覧」をCSV出力する際に、不具合が発生しています。

確認した発生条件：ラベルを複数設定
不具合内容：CSV出力時にラベルが複数設定されている艦だけステータス値が右にずれる

ご修正のほどお願いします。

**Comment by sanaehirotaka** [comment]
バージョン v18.2.3 で修正しました。
