### ISSUE TITLE
艦これサーバーのIP変更したっぽいです。

### ISSUE THREAD

**Issue by kikurinkei** [sanaehirotaka/logbook-kai#78]
艦これサーバーの仕様変更なのかなんなのかわかりませんが、
日誌でログ取得できませんでした。
リソースモニター　perfmon.exe 　で見ると203.104.209.183との通信してましたので、
串の設定を変更したところ問題なく日誌が取得しました。
いままでの設定IP　舞鶴鎮守府 125.6.187.205
新IP？　203.104.209.183
httpでトップディレクトリにアクセスすると　TEST WORLD 4
とありますので4番目のサバ、舞鶴専用ということなのかもしれません。ご一報まで。

**Comment by sanaehirotaka** [comment]
ありがとうございます v18.3.1 で対応しました！
