### ISSUE TITLE
ゲームが起動できません

### ISSUE THREAD

**Issue by f-4ej** [sanaehirotaka/logbook-kai#81]
舞鶴鎮守府所属ですが、18.3.2にバージョンアップしてから
ゲームが起動できません。
windows10でchromeを使用しています。

**Comment by sanaehirotaka** [comment]
こんにちは。
舞鎮は2/23のメンテ後にサーバーのIPアドレスが変更されており、その影響の可能性があります(プロキシの再設定をされていない場合、恐らくそれが原因です)。
- [ ] [ブラウザでのプロキシの再設定](https://github.com/sanaehirotaka/logbook-kai/blob/master/how-to-preference.md)
- [ ] ブラウザキャッシュの削除

をお試し下さい。

**Comment by f-4ej** [comment]
プロキシの再設定やキャッシュ削除もやってみましたが、
ダメです。
ぷかぷか丸すら出ずに、ゲーム部分が黒いままです。
KankoreSnifferは動くので、航海日誌の通信部分に
何かあるのではと考えているのですが・・・

**Comment by sanaehirotaka** [comment]
自分も舞鎮で正常にプレイできているので通常であれば動くと思うのですが。何故でしょうね
以下の改善策をお試しください。
- [ ] 通信プラグイン(logbook-kai-proxy-plugin.jar)利用している場合削除する(v18.3.1から改良版が内蔵されるようになりました)
- [ ] 航海日誌を再ダウンロードして上書きする(ダウンロードに失敗していた可能性)。

**Comment by f-4ej** [comment]
アドバイスありがとうございます。
　通信プラグインは使用していません。
　再ダウンロードして別フォルダに保存して実行してもダメでした。
　ログファイルを見ると、［アップデートチェックで例外］が発生しています。
　試しに旧バージョン（18.2.7）をダウンロードして実行しましたが、最新バージョンの通知が出ません。
通信部分を担うランタイムあたりが壊れてるのかなぁ

**Comment by sanaehirotaka** [comment]
通信自体ができないとなると、ファイアウォールやウイルス対策ソフトが通信をブロックしている可能性がありそうです。
ファイアウォール、ウイルス対策ソフトを一旦無効にして接続できるかどうかをお試し下さい。
接続できた場合は有効に戻してブロックリストに含まれていないかを確認して例外として登録下さい。

**Comment by f-4ej** [comment]
お世話になります
Windows Defenderをオフにしても状況変わらずです。
ログに次のような記述がありましたが、関係ありませんか？
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by sanaehirotaka** [comment]
>  Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
こちらJavaのバージョンが古いために証明書の検証が出来ないために起こっている例外です。
最新のJava8をインストールすると解決します。

>  Windows Defenderをオフにしても状況変わらずです。
Windows ファイアウォールは試されましたでしょうか？
それでも駄目なら、自分には策が無いですね…

**Comment by f-4ej** [comment]
ファイアウォールやJava再インストールも試しましたが
ダメでした。
SSL関連の障害のようなので復旧をあきらめ、windowsを初期化したところ
無事に航海日誌が使用できるようになりました。
いろいろとご迷惑をおかけしまして、すみませんでした。
本当にありがとうございました。
