### ISSUE TITLE
一覧の表示列およびフィルタの増強希望

### ISSUE THREAD

**Issue by ashiphide** [sanaehirotaka/logbook-kai#83]
一覧の表示項目を増やしていただきたく要望致します。

所有艦娘一覧
・速力
・耐久（現在HP/最大HP）
・射程

所有装備一覧
・戦闘行動半径

また、フィルタの増強もご検討いただければ。
案）
　下記3つのボックスを1セットにしたフィルタを2～3個用意し、絞り込みを行う。
　・「列名」を選択するボックス
　・「条件式」を選択するボックス（＞、≧、＝、＜、≦）
　・「条件値」を入力するボックス
艦娘一覧、装備一覧双方に欲しいです。

**Comment by Sdk0815** [comment]
遅くなりましたが、追加の表示列については既に対応済みで、残るフィルターの改善について先ほど実装を行いました。次のバージョンから利用可能です。
