### ISSUE TITLE
所有装備の数が少なく表示される

### ISSUE THREAD

**Issue by pandanahito** [sanaehirotaka/logbook-kai#85]
航海日誌で表示されている「所有装備」の数が艦隊司令部情報ページの「装備アイテム保有数」と一致していない
春イベントで通常存在していないアイテムが追加されている影響かもしれませんが最悪「装備アイテム保有数」オーバーでドロップ艦が落ちない現象が起きる可能性が危惧されます
調査よろしくお願いします

**Comment by sanaehirotaka** [comment]
ありがとうございます。
この現象は【食べ物】ミニイベントでお米からおにぎりを作る際に作られたおにぎりを認識していないために起こります。現象が発生した場合、ゲームを再スタートすることで装備の情報が同期されズレはなくなります。
次のバージョンで修正します。
