### ISSUE TITLE
通信ができません

### ISSUE THREAD

**Issue by udn20330** [sanaehirotaka/logbook-kai#88]
いつも航海日誌改を使わせてもらっています。

起きている症状を説明します
航海日誌改経由で接続している状況で
航海日誌の正規の終了動作以外の状況
（例えば航海日誌を起動したままWindowsを再起動した等）
が起こると
次回以降、
航海日誌を起動→ブラウザを起動→艦これを起動
とするとローディング画面（ぷかぷか丸）が表示されず
画面が白色のまま起動しないというものです

尚、ブラウザを航海日誌を通さずに起動すれば起動確認できました
複数のブラウザ（専用ブラウザ含）で試してみましたが
どれも同じ症状でした

ブラウザ側のキャッシュの削除等も試みましたが改善はせず
現状、CSVファイル（建造等のログ）を別の場所に移動、
それ以外（航海日誌改の実行環境）を全部削除
再度航海日誌改をダウンロード
再展開→ポート等の設定を行う→起動
すれば治るようです。

対応、対策等あれば教えて頂いてもよろしいでしょうか？
宜しくお願い致します

**Comment by sanaehirotaka** [comment]
うーん分からないですね
航海日誌がプロキシサーバーを起動できなかったorポートが間違っているが最も考えられる原因ですが
ブラウザが原因になっていることもあります、例えばFirefoxの場合航海日誌が起動していない状態でゲームを開始しようとするとプロキシ設定が一時的に無効になったりします（その場合Firefoxのプロキシ設定から[再読込]ボタンを押せば治ります）。
まずは航海日誌がプロキシサーバーを起動できているかをご確認ください。
確認方法の例ですがコマンドプロンプトを起動し
netstat /a /p TCP
と入力してください。起動できていれば次のような表示がされます(ポートを8888で設定している場合)
![image](https://user-images.githubusercontent.com/2179301/43840230-23f5a470-9b5b-11e8-9868-869c0485673d.png)

**Comment by udn20330** [comment]
あれから色々試しましたので報告を、
ゲームが起動してから航海日誌改に接続（ブラウザの接続先ポート変更）
を行えば普通につながることが分かりました
恐らくこちらの環境だと思いますので。
原因を調べようと思います。
ご迷惑をおかけしました！
