### ISSUE TITLE
MacとUbuntuで重い

### ISSUE THREAD

**Issue by manu3da4** [sanaehirotaka/logbook-kai#89]
いつも使わせていただき、ありがとうございます。
Win, Mac, Ubuntuで使っています。8.1からですが、お風呂に入りたい艦娘画面を出しておくと、Winは大丈夫なのですが、MacとUbuntuではスクロールもできないほど重くなってしまいます。リフレッシュする間隔を大きくできないでしょうか。

**Comment by sanaehirotaka** [comment]
テーブル行の描画方法を変更することで対処してみます

**Comment by manu3da4** [comment]
Mac+Chromeでは改善されました。対応ありがとうございました。
Ubuntu+Chromeでは重くなります。Ubuntu+Firefoxにすると大丈夫のようです。
あとはChrome側の問題でしょうか。
