### ISSUE TITLE
艦隊名のタブ表示のバグ

### ISSUE THREAD

**Issue by toro-cat** [sanaehirotaka/logbook-kai#9]
編成画面で艦隊名を変えた後、母港に戻ると、母港タブの遠征表示・各艦隊タブの頭の艦隊名は変更後で表示されるが、タブの表示が変更前のままになる。
再起動すると変更後の艦隊名で表示される。

**Comment by sanaehirotaka** [comment]
母港画面に戻った時に反映されるように修正します
