### ISSUE TITLE
所有艦娘一覧の画像の大きさを小さくする機能が欲しいです

### ISSUE THREAD

**Issue by maroncoro** [sanaehirotaka/logbook-kai#91]
所有艦娘一覧画像が大きくなりましたが行の幅が広がってしまい逆に見づらくなってしまいました。
以前のような大きさに切り替えられる機能が欲しいです。

**Comment by sanaehirotaka** [comment]
少しわかりにくいかもしれません。
[その他]-[設定]から[戦闘・艦隊]タブの[画像の拡大・縮小(%)]から変更が可能です。
![image](https://user-images.githubusercontent.com/2179301/44787473-31b18700-abd2-11e8-950c-e3e3c329a280.png)
65%でちょうど1期のサイズになります。
