### ISSUE TITLE
遠征の条件チェック

### ISSUE THREAD

**Issue by headsupsevens** [sanaehirotaka/logbook-kai#95]
東京急行（弐）を出す際に、ドラム缶を３隻しか積まずに失敗してしまったのですが、
遠征を出す際に警告のポップアップが出なかったように思います。
見逃していただけなら申し訳ありません・・・

**Comment by sanaehirotaka** [comment]
設定確認しましたがドラム缶4隻になってました。恐らく見逃しかと
[計算機]-[遠征条件確認]から各種遠征の条件と条件を満たしているかを確認出来ますのでご確認ください。またこの設定を遠征出撃時の警告表示と共用しています。[実際の設定ファイル](https://github.com/sanaehirotaka/logbook-kai/blob/master/src/main/resources/logbook/mission/38.json)
![image](https://user-images.githubusercontent.com/2179301/46289679-b96d2580-c5c4-11e8-9e55-03406d288e23.png)

**Comment by headsupsevens** [comment]
回答ありがとうございます。
色々編成をいじって遠征条件確認を見てみましたが、条件を満たさないとビックリマークつきますね。
見逃しただけっぽいですね。
（もしくはWindows側の何らかの理由でポップアップが出なかったとか・・・？）
取り下げさせてください。
