### ISSUE TITLE
所持艦娘一覧の装備画像縮小機能と通知トースト位置の変更機能が欲しい

### ISSUE THREAD

**Issue by Lyokamoto** [sanaehirotaka/logbook-kai#97]
いつも大変便利に使わせていただいています。ありがとうございます。

所持艦娘一覧で現在、艦娘画像の縮小設定はありますが、装備画像、札画像の縮小設定をお願いできないでしょうか？より狭いスペースに多くの艦娘データを表示させることが目的です。
現在艦娘画像の縮小率28%で運用していますが、装備画像や札画像が入ると行縦幅がそれに合わせて拡大されてしまうようなので、こちらも艦娘画像と同様に縮小できればと考えています。

また、艦娘大破時や遠征条件不適合の際のアラートで表示されるトーストについて、現在は右下に表示されるようですが、こちらの位置も画面の右上、右下、左上、左下などで自由に設定できると嬉しいです。（当方、艦これ画面を右上、logbookを右下に配置してプレイするスタイルのため、より気付きやすい位置（右上）に表示させたいのです）

ちなみにプレイ環境はMac OS10.13です

**Comment by Sdk0815** [comment]
前半の部分（画像の縮小）に関しては既に実装済みでしたが、さきほどトースト位置の変更機能の実装も行いました。次のバージョンで確認できます。
