### ISSUE TITLE
バージョン情報のリンク先に飛べない

### ISSUE THREAD

**Issue by sherry0757** [sanaehirotaka/logbook-kai#98]
Linuxでバージョン情報の「ダウンロードサイトを開く」、「不具合や要望を報告する」をクリックすると反応がありません。
メイン画面 任務の検索も同じく反応がありません。

**Comment by sanaehirotaka** [comment]
デフォルトのブラウザが見つからない(設定されていない)可能性があります。
LinuxのディストリビューションとJavaのベンダーは何をお使いでしょうか。

**Comment by sherry0757** [comment]
Linux Mint 19 mate 64bit oracle 1.8.0_181です。

oracle 10.0.2に切り替えてみたらリンクは飛べて問題ありませんでした。
その代わり所有装備、所有艦娘が開けませんでした。(java8は開ける)

Linux使い始めてまだ二ヶ月なので、自分が何か間違えてる可能性も

**Comment by sanaehirotaka** [comment]
Linux Mintですか、試してみます。
> oracle 10.0.2に切り替えてみたらリンクは飛べて問題ありませんでした。
> その代わり所有装備、所有艦娘が開けませんでした。(java8は開ける)
logbook-kaiはJava8で動作します。Java9以降は対応していないため動作しませんのでご注意ください。

**Comment by sanaehirotaka** [comment]
Linux Mint 19 mate + OpenJDK 8 OpenJFX で再現しました。
仮の修正版をリリースしましたのでこちらを手動で更新してご確認ください。
https://github.com/sanaehirotaka/logbook-kai/releases/tag/v18.10.2-SNAPSHOT

**Comment by sherry0757** [comment]
ありがとうございます。 こちらでも使えるの確認しました。
